#!/usr/bin/env python3
"""
Read reference pairs from binary file generated by test_transport_reference.cpp

Binary format:
    Header:
        uint32_t magic = 0x4C575246  ("LWRF")
        uint32_t version = 1
        uint32_t num_pairs
        uint32_t radial_len (80)
        uint32_t num_frames (100)

    Per pair:
        float params[6]  (offset, persistence, diffusion, dt, amount, spread)
        uint16_t final_state_16bit[80*3]  (radial × RGB, uint16)
        uint8_t final_state_8bit[80*3]    (radial × RGB, uint8 after tone map)

Usage:
    import read_reference
    data = read_reference.read_reference_file('reference_pairs.bin')
    print(f"Loaded {data['params'].shape[0]} pairs")
    print(f"Parameter ranges: {data['param_ranges']}")
"""

import struct
import numpy as np
from pathlib import Path

MAGIC = 0x4C575246  # "LWRF"
VERSION = 1
RADIAL_LEN = 80
NUM_FRAMES = 100


def read_reference_file(filepath):
    """
    Read reference pairs from binary file.

    Args:
        filepath: Path to reference_pairs.bin

    Returns:
        dict with keys:
            'params': numpy array [N, 6] float32 (offset, persistence, diffusion, dt, amount, spread)
            'state_16bit': numpy array [N, 80, 3] uint16 (radial history)
            'state_8bit': numpy array [N, 80, 3] uint8 (tone-mapped output)
            'param_ranges': dict with min/max for each parameter
            'num_pairs': number of pairs
    """
    filepath = Path(filepath)

    if not filepath.exists():
        raise FileNotFoundError(f"Reference file not found: {filepath}")

    with open(filepath, 'rb') as f:
        # Read header
        magic, version, num_pairs, radial_len, num_frames = struct.unpack(
            '<IIIII',
            f.read(5 * 4)
        )

        if magic != MAGIC:
            raise ValueError(f"Invalid magic: {hex(magic)} (expected {hex(MAGIC)})")
        if version != VERSION:
            raise ValueError(f"Invalid version: {version} (expected {VERSION})")
        if radial_len != RADIAL_LEN:
            raise ValueError(f"Invalid radial_len: {radial_len} (expected {RADIAL_LEN})")
        if num_frames != NUM_FRAMES:
            raise ValueError(f"Invalid num_frames: {num_frames} (expected {NUM_FRAMES})")

        # Allocate output arrays
        params = np.zeros((num_pairs, 6), dtype=np.float32)
        state_16bit = np.zeros((num_pairs, RADIAL_LEN, 3), dtype=np.uint16)
        state_8bit = np.zeros((num_pairs, RADIAL_LEN, 3), dtype=np.uint8)

        # Read pairs
        for i in range(num_pairs):
            # Read params
            param_data = f.read(6 * 4)
            if len(param_data) < 24:
                raise EOFError(f"Unexpected EOF reading params for pair {i}")
            params[i] = struct.unpack('<ffffff', param_data)

            # Read 16-bit state
            hist_data = f.read(RADIAL_LEN * 3 * 2)
            if len(hist_data) < RADIAL_LEN * 3 * 2:
                raise EOFError(f"Unexpected EOF reading 16-bit state for pair {i}")
            state_16bit[i] = np.frombuffer(hist_data, dtype=np.uint16).reshape(RADIAL_LEN, 3)

            # Read 8-bit state
            byte_data = f.read(RADIAL_LEN * 3 * 1)
            if len(byte_data) < RADIAL_LEN * 3:
                raise EOFError(f"Unexpected EOF reading 8-bit state for pair {i}")
            state_8bit[i] = np.frombuffer(byte_data, dtype=np.uint8).reshape(RADIAL_LEN, 3)

    # Compute parameter ranges
    param_names = ['offset', 'persistence', 'diffusion', 'dt', 'amount', 'spread']
    param_ranges = {}
    for j, name in enumerate(param_names):
        param_ranges[name] = {
            'min': float(params[:, j].min()),
            'max': float(params[:, j].max()),
            'unique': len(np.unique(params[:, j]))
        }

    return {
        'params': params,
        'state_16bit': state_16bit,
        'state_8bit': state_8bit,
        'num_pairs': num_pairs,
        'param_ranges': param_ranges,
    }


def print_stats(data):
    """Print summary statistics about loaded reference data."""
    print(f"Loaded {data['num_pairs']} reference pairs")
    print(f"State shape (16-bit): {data['state_16bit'].shape}")
    print(f"State shape (8-bit): {data['state_8bit'].shape}")
    print()

    print("Parameter ranges:")
    for name, ranges in data['param_ranges'].items():
        print(f"  {name:12s}: {ranges['min']:8.6f} to {ranges['max']:8.6f} ({ranges['unique']:3d} unique values)")
    print()

    print("16-bit state statistics:")
    print(f"  Mean:   {data['state_16bit'].astype(np.float32).mean():.1f}")
    print(f"  Std:    {data['state_16bit'].astype(np.float32).std():.1f}")
    print(f"  Min:    {data['state_16bit'].min()}")
    print(f"  Max:    {data['state_16bit'].max()}")
    print()

    print("8-bit state statistics:")
    print(f"  Mean:   {data['state_8bit'].astype(np.float32).mean():.1f}")
    print(f"  Std:    {data['state_8bit'].astype(np.float32).std():.1f}")
    print(f"  Min:    {data['state_8bit'].min()}")
    print(f"  Max:    {data['state_8bit'].max()}")
    print()

    # Check for all-zero outputs (sanity check)
    all_zero_16 = (data['state_16bit'].sum(axis=(1, 2)) == 0).sum()
    all_zero_8 = (data['state_8bit'].sum(axis=(1, 2)) == 0).sum()
    print(f"All-zero outputs: {all_zero_16} (16-bit), {all_zero_8} (8-bit)")


if __name__ == '__main__':
    import sys

    if len(sys.argv) > 1:
        filepath = sys.argv[1]
    else:
        filepath = '/sessions/adoring-festive-clarke/mnt/firmware-v3/testbed/data/reference_pairs.bin'

    try:
        data = read_reference_file(filepath)
        print_stats(data)
    except FileNotFoundError:
        print(f"Error: {filepath} not found")
        print("Run: pio run -e native_test")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading reference file: {e}")
        sys.exit(1)
