#!/usr/bin/env python3
"""
SpectraSynq LUT Generator - God Tier Optimization
Generates compile-time lookup tables for the definitive Goertzel engine
"""

import math

# SACRED MUSICAL FREQUENCIES - A0 to A7, every semitone
MUSIC_FREQUENCIES = [
    # Octave 0-1 (A0-G#1): Deep bass fundamentals
    27.50, 29.14, 30.87, 32.70, 34.65, 36.71, 38.89, 41.20, 43.65, 46.25, 49.00, 51.91,
    55.00, 58.27, 61.74, 65.41, 69.30, 73.42, 77.78, 82.41, 87.31, 92.50, 98.00, 103.83,
    
    # Octave 2-3 (A2-G#3): Bass range - kick drums, bass guitars  
    110.00, 116.54, 123.47, 130.81, 138.59, 146.83, 155.56, 164.81, 174.61, 185.00, 196.00, 207.65,
    220.00, 233.08, 246.94, 261.63, 277.18, 293.66, 311.13, 329.63, 349.23, 369.99, 392.00, 415.30,
    
    # Octave 4-5 (A4-G#5): Midrange - vocals, instruments
    440.00, 466.16, 493.88, 523.25, 554.37, 587.33, 622.25, 659.25, 698.46, 739.99, 783.99, 830.61,
    880.00, 932.33, 987.77, 1046.50, 1108.73, 1174.66, 1244.51, 1318.51, 1396.91, 1479.98, 1567.98, 1661.22,
    
    # Octave 6-7 (A6-G#7): High range - harmonics, brilliance
    1760.00, 1864.66, 1975.53, 2093.00, 2217.46, 2349.32, 2489.02, 2637.02, 2793.83, 2959.96, 3135.96, 3322.44,
    3520.00, 3729.31, 3951.07, 4186.01, 4434.92, 4698.63, 4978.03, 5274.04, 5587.65, 5919.91, 6271.93, 6644.88
]

SAMPLE_RATE = 16000.0
PI = math.pi

def generate_goertzel_coeffs():
    """Generate Goertzel coefficients: 2.0 * cos(2*PI*f/Fs)"""
    coeffs = []
    for freq in MUSIC_FREQUENCIES:
        omega = (2.0 * PI * freq) / SAMPLE_RATE
        coeff = 2.0 * math.cos(omega)
        coeffs.append(coeff)
    return coeffs

def generate_magnitude_cos_terms():
    """Generate cosine terms for magnitude calculation"""
    cos_terms = []
    for freq in MUSIC_FREQUENCIES:
        omega = (2.0 * PI * freq) / SAMPLE_RATE
        cos_term = math.cos(omega)
        cos_terms.append(cos_term)
    return cos_terms

def generate_magnitude_sin_terms():
    """Generate sine terms for magnitude calculation"""
    sin_terms = []
    for freq in MUSIC_FREQUENCIES:
        omega = (2.0 * PI * freq) / SAMPLE_RATE
        sin_term = math.sin(omega)
        sin_terms.append(sin_term)
    return sin_terms

def format_array(name, values, precision=6):
    """Format array for C++ constexpr declaration"""
    lines = [f"constexpr float {name}[96] = {{"]
    
    for i in range(0, len(values), 4):  # 4 values per line
        chunk = values[i:i+4]
        formatted_values = [f"{val:.{precision}f}f" for val in chunk]
        line = "    " + ", ".join(formatted_values)
        if i + 4 < len(values):
            line += ","
        lines.append(line)
    
    lines.append("};")
    return "\n".join(lines)

def main():
    print("=== SpectraSynq LUT Generator ===")
    print("Forging the God-Tier Goertzel Engine...")
    
    # Generate all LUTs
    goertzel_coeffs = generate_goertzel_coeffs()
    mag_cos_terms = generate_magnitude_cos_terms()
    mag_sin_terms = generate_magnitude_sin_terms()
    
    # Generate C++ header content
    header = """/*
 * SpectraSynq God-Tier Goertzel LUTs
 * Pre-computed at compile time for maximum performance
 * Generated by: generate_luts.py
 * 
 * MUSICAL FIDELITY: Exact semitone frequencies A0-A7
 * BRUTAL EFFICIENCY: Zero runtime trig calculations
 * CACHE DOMINANCE: Optimal memory layout
 */

#ifndef GOERTZEL_LUTS_H
#define GOERTZEL_LUTS_H

// Sample rate for all calculations
constexpr float GOERTZEL_SAMPLE_RATE = 16000.0f;

// Number of frequency bins (A0 to A7, every semitone)
constexpr int GOERTZEL_BINS = 96;

// SACRED MUSICAL FREQUENCIES - The source of truth
constexpr float MUSIC_FREQUENCIES[96] = {"""
    
    # Add frequency array
    for i in range(0, len(MUSIC_FREQUENCIES), 4):
        chunk = MUSIC_FREQUENCIES[i:i+4]
        formatted_freqs = [f"{freq:.2f}f" for freq in chunk]
        header += "\n    " + ", ".join(formatted_freqs)
        if i + 4 < len(MUSIC_FREQUENCIES):
            header += ","
    
    header += "\n};\n\n"
    
    # Add LUT arrays
    header += "// PRE-COMPUTED GOERTZEL COEFFICIENTS\n"
    header += "// 2.0 * cos(2*PI*f/Fs) for each frequency\n"
    header += format_array("GOERTZEL_COEFFS", goertzel_coeffs) + "\n\n"
    
    header += "// PRE-COMPUTED MAGNITUDE COSINE TERMS\n"
    header += "// cos(2*PI*f/Fs) for magnitude calculation\n"
    header += format_array("MAG_COS_TERMS", mag_cos_terms) + "\n\n"
    
    header += "// PRE-COMPUTED MAGNITUDE SINE TERMS\n"
    header += "// sin(2*PI*f/Fs) for magnitude calculation\n"
    header += format_array("MAG_SIN_TERMS", mag_sin_terms) + "\n\n"
    
    header += "#endif // GOERTZEL_LUTS_H"
    
    # Write header file
    with open('/Users/macbookpro/Downloads/Emotiscope-1.1/AP_SOT/include/audio/goertzel_luts.h', 'w') as f:
        f.write(header)
    
    print(f"✅ Generated LUTs for {len(MUSIC_FREQUENCIES)} musical frequencies")
    print(f"✅ Frequency range: {MUSIC_FREQUENCIES[0]:.1f}Hz to {MUSIC_FREQUENCIES[-1]:.1f}Hz")
    print(f"✅ Goertzel coefficients: {len(goertzel_coeffs)} values")
    print(f"✅ Magnitude terms: {len(mag_cos_terms)} cos + {len(mag_sin_terms)} sin")
    print("✅ Header written to: include/audio/goertzel_luts.h")
    print("\n🚀 THE GOERTZEL ENGINE STANDS READY FOR REFORGING!")

if __name__ == "__main__":
    main()