name: LightwaveOS
options:
  bundleIdPrefix: com.spectrasynq
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

configs:
  Debug: debug
  DebugCpp: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: "RIVE_RUNTIME_APPLE"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    ENABLE_PREVIEWS: true

targets:
  LightwaveOS:
    type: application
    platform: iOS
    sources:
      - path: LightwaveOS
        excludes:
          - "**/.DS_Store"
          - "**/CLAUDE.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spectrasynq.lightwaveos2
        MARKETING_VERSION: "2.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: "LightwaveOS v2"
        INFOPLIST_KEY_NSLocalNetworkUsageDescription: "LightwaveOS needs to discover LED controllers on your local network."
        INFOPLIST_KEY_NSBonjourServices: "_lightwaveos._tcp,_http._tcp"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: VS4NV74375
        CODE_SIGN_ENTITLEMENTS: LightwaveOS.entitlements
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "RIVE_RUNTIME_APPLE DEBUG"
        DebugCpp:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "RIVE_RUNTIME_CPP DEBUG"
    dependencies:
      - package: RiveRuntime
        product: RiveRuntime
    info:
      path: LightwaveOS/Resources/Info.plist
      properties:
        CFBundleDisplayName: "LightwaveOS v2"
        NSLocationWhenInUseUsageDescription: "LightwaveOS uses your location to detect which WiFi network you're on for instant device connection."
        NSLocalNetworkUsageDescription: "LightwaveOS needs to discover LED controllers on your local network."
        NSBonjourServices:
          - "_lightwaveos._tcp"
          - "_http._tcp"
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        UIBackgroundModes: []
        UILaunchScreen: {}

  LightwaveOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LightwaveOSTests
    dependencies:
      - target: LightwaveOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spectrasynq.lightwaveos2.tests
        GENERATE_INFOPLIST_FILE: YES

  LightwaveOSUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LightwaveOSUITests
    dependencies:
      - target: LightwaveOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.spectrasynq.lightwaveos2.uitests
        GENERATE_INFOPLIST_FILE: YES

packages:
  RiveRuntime:
    url: https://github.com/rive-app/rive-ios
    from: 6.12.2
