// ============================================================================
// EdgeMixer -> K1 golden-master parity oracle (Step 0 of the port plan).
//
// Purpose (test infrastructure only; no device behaviour changes):
//   Freeze the LightwaveOS EdgeMixer colour maths as golden input->output
//   vectors by driving the REAL EdgeMixer::process(), then prove that a
//   fixed-point Q15.16 reference port (the code that will transplant to the
//   K1 SensoryBridge lineage, SQ15x16 0..1 channels) reproduces those vectors
//   within +/-1 LSB per channel. The largest port risk is silent fixed-point
//   corruption (8-bit maths on a 0..1 channel is ~256x wrong and still
//   compiles); this oracle kills that risk before any K1 code is written.
//
// Fidelity discipline:
//   - Goldens are generated by the REAL process() (never re-implemented maths).
//   - At strength 255 / UNIFORM spatial / STATIC temporal the process() path is
//     a pure direct-assign of computeTransform() for pixels with max channel
//     >= 2, and an untouched passthrough for near-black pixels (maxC < 2).
//   - The Q15.16 reference mirrors recomputeMatrix() (identical float formulae,
//     stored at FULL Q15.16 precision as K1 will) + computeTransform() (a
//     normalised-0..1 3x3 multiply, clamp, back to 8-bit).
//
// British English throughout (colour, centre, behaviour, initialise).
// Reference source: src/effects/enhancement/EdgeMixer.h (UNMODIFIED).
// ============================================================================

#include <unity.h>

#include <cstdint>
#include <cstring>
#include <cstdio>
#include <cmath>
#include <fstream>
#include <algorithm>

// EdgeMixer.h uses M_PI, which is not guaranteed under strict -std=c++17 on
// some hosts (Apple libc defines __STRICT_ANSI__ and gates M_PI). Provide it
// BEFORE including the header so the header's config-time maths compiles. The
// production header is NOT modified. Guarded so a host that already supplies
// M_PI is untouched (identical value avoids any redefinition warning).
#ifndef M_PI
#define M_PI 3.14159265358979323846264338327950288
#endif

#include "effects/enhancement/EdgeMixer.h"

using lightwaveos::enhancement::EdgeMixer;
using lightwaveos::enhancement::EdgeMixerMode;
using lightwaveos::enhancement::EdgeMixerSpatial;
using lightwaveos::enhancement::EdgeMixerTemporal;
using lightwaveos::audio::ControlBusFrame;

// ----------------------------------------------------------------------------
// Test grid
// ----------------------------------------------------------------------------

namespace {

// The six signal-independent colour-harmony modes (Tier 1 of the port). STM
// modes 7/8 are excluded — they consume audio signals absent from K1.
constexpr EdgeMixerMode kModes[] = {
    EdgeMixerMode::ANALOGOUS,            // 1
    EdgeMixerMode::COMPLEMENTARY,        // 2
    EdgeMixerMode::SPLIT_COMPLEMENTARY,  // 3
    EdgeMixerMode::SATURATION_VEIL,      // 4
    EdgeMixerMode::TRIADIC,              // 5
    EdgeMixerMode::TETRADIC,             // 6
};
constexpr int kNumModes = sizeof(kModes) / sizeof(kModes[0]);

constexpr uint8_t kSpreads[] = {0, 15, 30, 45, 60};
constexpr int kNumSpreads = sizeof(kSpreads) / sizeof(kSpreads[0]);

struct Probe {
    const char* name;
    uint8_t r, g, b;
    bool nearBlack;  // true when max channel < 2 (process() passes it through)
};

// 24-colour probe palette (all max(r,g,b) >= 2) + 3 near-black passthrough
// probes. Chosen to exercise primaries, secondaries, greys, skin tones and
// saturated hues — the colours most likely to expose fixed-point divergence.
constexpr Probe kPalette[] = {
    // Primaries
    {"red",          255,   0,   0, false},
    {"green",          0, 255,   0, false},
    {"blue",           0,   0, 255, false},
    // Secondaries
    {"yellow",       255, 255,   0, false},
    {"cyan",           0, 255, 255, false},
    {"magenta",      255,   0, 255, false},
    // Greys (grey axis — should map ~unchanged for hue rotations)
    {"white",        255, 255, 255, false},
    {"grey192",      192, 192, 192, false},
    {"grey128",      128, 128, 128, false},
    {"grey64",        64,  64,  64, false},
    {"grey8",          8,   8,   8, false},
    // Saturated hues
    {"orange",       255, 128,   0, false},
    {"springgreen",    0, 255, 128, false},
    {"azure",          0, 128, 255, false},
    {"rose",         255,   0, 128, false},
    {"violet",       128,   0, 255, false},
    {"chartreuse",   128, 255,   0, false},
    // Skin tones
    {"skin_light",   255, 219, 172, false},
    {"skin_medium",  198, 134,  66, false},
    {"skin_dark",    141,  85,  36, false},
    // Misc saturated / dim
    {"teal",           0, 200, 180, false},
    {"warm",         255,  80,  20, false},
    {"dim_blue",      10,  20,  40, false},
    {"deep_purple",   90,   0, 140, false},
    // Near-black passthrough probes (maxC < 2 -> untouched by process())
    {"black",          0,   0,   0, true},
    {"near_1",         1,   1,   1, true},
    {"near_r1",        1,   0,   1, true},
};
constexpr int kNumProbes = sizeof(kPalette) / sizeof(kPalette[0]);
constexpr int kNearBlackCount = 3;

// ----------------------------------------------------------------------------
// Golden store
// ----------------------------------------------------------------------------

struct GoldenRow {
    uint8_t mode;
    uint8_t spread;
    uint8_t in_r, in_g, in_b;
    uint8_t out_r, out_g, out_b;
    bool nearBlack;
};

constexpr int kMaxRows = kNumModes * kNumSpreads * kNumProbes;
GoldenRow g_golden[kMaxRows];
int g_goldenCount = 0;

bool g_csvOk = false;
int g_csvRows = 0;

// ----------------------------------------------------------------------------
// Q15.16 fixed-point reference port (mirrors what transplants to K1)
//
// recomputeMatrix: identical float formulae to EdgeMixer::recomputeMatrix,
//                  result stored at FULL Q15.16 precision (int32, 16 frac bits)
//                  — this is the SQ15x16 matrix K1 will hold.
// computeTransform: normalise uint8 0..255 -> Q15.16 0..1, 3x3 multiply in
//                   int64, round back to Q15.16, clamp [0,1], convert to uint8.
// ----------------------------------------------------------------------------

constexpr int32_t kQ16One = 65536;  // 1.0 in Q15.16

struct RefMatrix {
    int32_t m[9];  // Q15.16, row-major
};

// Mirror EdgeMixer::setSpread's integer m_satScale derivation exactly
// (255 - spreadDegrees * 230 / 60, integer division).
uint8_t refSatScale(uint8_t spreadDegrees) {
    if (spreadDegrees > 60) spreadDegrees = 60;
    return static_cast<uint8_t>(255 - (static_cast<uint16_t>(spreadDegrees) * 230 / 60));
}

RefMatrix refRecomputeMatrix(EdgeMixerMode mode, uint8_t spreadDegrees) {
    // Identical to EdgeMixer::recomputeMatrix() — same float type, same order,
    // same constants — so the only divergence under test is Q8.8 (source) vs
    // Q15.16 (reference) quantisation of the SAME float matrix.
    float mat[9] = {1, 0, 0,  0, 1, 0,  0, 0, 1};

    float theta = 0.0f;
    float satRetain = 1.0f;

    switch (mode) {
        case EdgeMixerMode::ANALOGOUS:
            theta = static_cast<float>(spreadDegrees) * (static_cast<float>(M_PI) / 180.0f);
            break;
        case EdgeMixerMode::COMPLEMENTARY:
            theta = static_cast<float>(M_PI);
            satRetain = 217.0f / 255.0f;
            break;
        case EdgeMixerMode::SPLIT_COMPLEMENTARY:
            theta = 150.0f * (static_cast<float>(M_PI) / 180.0f);
            satRetain = 230.0f / 255.0f;
            break;
        case EdgeMixerMode::SATURATION_VEIL:
            satRetain = static_cast<float>(refSatScale(spreadDegrees)) / 255.0f;
            break;
        case EdgeMixerMode::TRIADIC:
            theta = 120.0f * (static_cast<float>(M_PI) / 180.0f);
            satRetain = 1.0f - (static_cast<float>(spreadDegrees) / 60.0f) * 0.30f;
            break;
        case EdgeMixerMode::TETRADIC:
            theta = 90.0f * (static_cast<float>(M_PI) / 180.0f);
            satRetain = 1.0f - (static_cast<float>(spreadDegrees) / 60.0f) * 0.30f;
            break;
        default:
            break;  // MIRROR / STM — not exercised here; identity retained.
    }

    if (theta != 0.0f) {
        const float cosT = cosf(theta);
        const float sinT = sinf(theta);
        const float oneMinusCos = 1.0f - cosT;
        const float third = oneMinusCos / 3.0f;
        const float sqrt13 = 0.57735026919f;  // sqrt(1/3)
        const float sinTerm = sqrt13 * sinT;

        mat[0] = cosT + third;
        mat[1] = third - sinTerm;
        mat[2] = third + sinTerm;
        mat[3] = third + sinTerm;
        mat[4] = cosT + third;
        mat[5] = third - sinTerm;
        mat[6] = third - sinTerm;
        mat[7] = third + sinTerm;
        mat[8] = cosT + third;
    }

    if (satRetain < 1.0f) {
        const float Lr = 0.299f;
        const float Lg = 0.587f;
        const float Lb = 0.114f;
        const float inv = 1.0f - satRetain;

        float d[9] = {
            satRetain + inv * Lr,  inv * Lg,              inv * Lb,
            inv * Lr,              satRetain + inv * Lg,  inv * Lb,
            inv * Lr,              inv * Lg,              satRetain + inv * Lb
        };

        float combined[9];
        for (int row = 0; row < 3; ++row) {
            for (int col = 0; col < 3; ++col) {
                combined[row * 3 + col] =
                    d[row * 3 + 0] * mat[0 * 3 + col] +
                    d[row * 3 + 1] * mat[1 * 3 + col] +
                    d[row * 3 + 2] * mat[2 * 3 + col];
            }
        }
        memcpy(mat, combined, sizeof(mat));
    }

    // FULL Q15.16 conversion (the K1 SQ15x16 target — NOT Q8.8-quantised).
    RefMatrix out;
    for (int i = 0; i < 9; ++i) {
        out.m[i] = static_cast<int32_t>(lroundf(mat[i] * 65536.0f));
    }
    return out;
}

inline uint8_t refClamp255(int64_t v) {
    if (v < 0) return 0;
    if (v > 255) return 255;
    return static_cast<uint8_t>(v);
}

// uint8 0..255 -> normalised Q15.16 0..1 (round-to-nearest). Mirrors converting
// a CRGB channel into a CRGB16 SQ15x16 0..1 channel on K1.
inline int32_t refToQ16(uint8_t u) {
    return static_cast<int32_t>((static_cast<uint32_t>(u) * 65536u + 127u) / 255u);
}

CRGB refComputeTransform(const RefMatrix& M, const CRGB& in) {
    const int32_t nr = refToQ16(in.r);
    const int32_t ng = refToQ16(in.g);
    const int32_t nb = refToQ16(in.b);

    // Q15.16 * Q15.16 -> Q31.32 accumulation in int64, then >>16 (rounded).
    const int64_t ro = static_cast<int64_t>(M.m[0]) * nr +
                       static_cast<int64_t>(M.m[1]) * ng +
                       static_cast<int64_t>(M.m[2]) * nb;
    const int64_t go = static_cast<int64_t>(M.m[3]) * nr +
                       static_cast<int64_t>(M.m[4]) * ng +
                       static_cast<int64_t>(M.m[5]) * nb;
    const int64_t bo = static_cast<int64_t>(M.m[6]) * nr +
                       static_cast<int64_t>(M.m[7]) * ng +
                       static_cast<int64_t>(M.m[8]) * nb;

    int32_t rq = static_cast<int32_t>((ro + 32768) >> 16);
    int32_t gq = static_cast<int32_t>((go + 32768) >> 16);
    int32_t bq = static_cast<int32_t>((bo + 32768) >> 16);

    // Clamp to [0, 1] in Q15.16.
    if (rq < 0) rq = 0; else if (rq > kQ16One) rq = kQ16One;
    if (gq < 0) gq = 0; else if (gq > kQ16One) gq = kQ16One;
    if (bq < 0) bq = 0; else if (bq > kQ16One) bq = kQ16One;

    // Q15.16 0..1 -> uint8 0..255 (round-to-nearest).
    CRGB result;
    result.r = refClamp255((static_cast<int64_t>(rq) * 255 + 32768) >> 16);
    result.g = refClamp255((static_cast<int64_t>(gq) * 255 + 32768) >> 16);
    result.b = refClamp255((static_cast<int64_t>(bq) * 255 + 32768) >> 16);
    return result;
}

// Mirrors process() at strength 255 / UNIFORM / STATIC: near-black passthrough,
// otherwise a direct assign of computeTransform().
CRGB refApply(const RefMatrix& M, const CRGB& in) {
    const uint8_t maxC = (in.r > in.g) ? ((in.r > in.b) ? in.r : in.b)
                                       : ((in.g > in.b) ? in.g : in.b);
    if (maxC < 2) return in;
    return refComputeTransform(M, in);
}

// Optional coefficient perturbation used by the fault-evidence test.
RefMatrix refMatrixFor(EdgeMixerMode mode, uint8_t spread,
                       int perturbIndex, int32_t perturbQ16) {
    RefMatrix M = refRecomputeMatrix(mode, spread);
    if (perturbIndex >= 0 && perturbIndex < 9) {
        M.m[perturbIndex] += perturbQ16;
    }
    return M;
}

// ----------------------------------------------------------------------------
// Golden generation — drive the REAL EdgeMixer::process()
// ----------------------------------------------------------------------------

void generateGoldensAndCsv() {
    g_goldenCount = 0;

    EdgeMixer& em = EdgeMixer::getInstance();

    std::ofstream csv(EDGEMIXER_GOLDEN_CSV);
    g_csvOk = csv.is_open();
    if (g_csvOk) {
        csv << "mode,spread,in_r,in_g,in_b,out_r,out_g,out_b\n";
    }
    g_csvRows = 0;

    CRGB strip2[kNumProbes];

    for (int mi = 0; mi < kNumModes; ++mi) {
        for (int si = 0; si < kNumSpreads; ++si) {
            const EdgeMixerMode mode = kModes[mi];
            const uint8_t spread = kSpreads[si];

            // Configure for the maximum-fidelity direct-assign path: full
            // strength, uniform spatial mask, static temporal (audio-agnostic).
            em.setMode(mode);
            em.setSpread(spread);
            em.setStrength(255);
            em.setSpatial(EdgeMixerSpatial::UNIFORM);
            em.setTemporal(EdgeMixerTemporal::STATIC);

            for (int p = 0; p < kNumProbes; ++p) {
                strip2[p] = CRGB(kPalette[p].r, kPalette[p].g, kPalette[p].b);
            }

            // Zero audio frame — STATIC temporal ignores it, but it must be a
            // valid, fully default-initialised contract frame.
            ControlBusFrame zeroFrame{};
            em.process(nullptr, strip2, static_cast<uint16_t>(kNumProbes), zeroFrame);

            for (int p = 0; p < kNumProbes; ++p) {
                GoldenRow& row = g_golden[g_goldenCount++];
                row.mode = static_cast<uint8_t>(mode);
                row.spread = spread;
                row.in_r = kPalette[p].r;
                row.in_g = kPalette[p].g;
                row.in_b = kPalette[p].b;
                row.out_r = strip2[p].r;
                row.out_g = strip2[p].g;
                row.out_b = strip2[p].b;
                row.nearBlack = kPalette[p].nearBlack;

                if (g_csvOk) {
                    csv << static_cast<int>(row.mode) << ','
                        << static_cast<int>(row.spread) << ','
                        << static_cast<int>(row.in_r) << ','
                        << static_cast<int>(row.in_g) << ','
                        << static_cast<int>(row.in_b) << ','
                        << static_cast<int>(row.out_r) << ','
                        << static_cast<int>(row.out_g) << ','
                        << static_cast<int>(row.out_b) << '\n';
                    ++g_csvRows;
                }
            }
        }
    }

    if (g_csvOk) csv.close();
}

int absDelta(int a, int b) { return (a > b) ? (a - b) : (b - a); }

}  // namespace

// ----------------------------------------------------------------------------
// Tests
// ----------------------------------------------------------------------------

// TASK 3 — parity: the Q15.16 reference reproduces every golden within +/-1 LSB.
void test_parity_within_one_lsb(void) {
    TEST_ASSERT_GREATER_THAN_INT(0, g_goldenCount);

    int worst = 0;
    int worstMode = 0, worstSpread = 0;
    uint8_t worstIn[3] = {0, 0, 0};

    for (int i = 0; i < g_goldenCount; ++i) {
        const GoldenRow& row = g_golden[i];
        const RefMatrix M =
            refRecomputeMatrix(static_cast<EdgeMixerMode>(row.mode), row.spread);
        const CRGB in(row.in_r, row.in_g, row.in_b);
        const CRGB out = refApply(M, in);

        const int dr = absDelta(out.r, row.out_r);
        const int dg = absDelta(out.g, row.out_g);
        const int db = absDelta(out.b, row.out_b);
        const int d = (dr > dg) ? ((dr > db) ? dr : db) : ((dg > db) ? dg : db);
        if (d > worst) {
            worst = d;
            worstMode = row.mode;
            worstSpread = row.spread;
            worstIn[0] = row.in_r; worstIn[1] = row.in_g; worstIn[2] = row.in_b;
        }
    }

    // Report the tightest bound achieved (safe in pio test output).
    char msg[160];
    std::snprintf(msg, sizeof(msg),
                  "max |ref-golden| = %d LSB (mode %d spread %d in %u,%u,%u) over %d vectors",
                  worst, worstMode, worstSpread,
                  worstIn[0], worstIn[1], worstIn[2], g_goldenCount);
    std::printf("[PARITY] %s\n", msg);
    std::fflush(stdout);
    TEST_ASSERT_LESS_OR_EQUAL_INT_MESSAGE(1, worst, msg);
}

// Near-black probes (maxC < 2) must pass through process() UNCHANGED.
void test_near_black_passthrough(void) {
    int checked = 0;
    for (int i = 0; i < g_goldenCount; ++i) {
        const GoldenRow& row = g_golden[i];
        if (!row.nearBlack) continue;
        TEST_ASSERT_EQUAL_UINT8(row.in_r, row.out_r);
        TEST_ASSERT_EQUAL_UINT8(row.in_g, row.out_g);
        TEST_ASSERT_EQUAL_UINT8(row.in_b, row.out_b);
        ++checked;
    }
    // Every (mode,spread) config contributes the near-black probes.
    TEST_ASSERT_EQUAL_INT(kNumModes * kNumSpreads * kNearBlackCount, checked);
}

// TASK 4 — fault-evidence: perturb ONE reference matrix coefficient by >=2 LSB
// and prove the parity check goes RED for at least one vector; the restored
// matrix goes GREEN. A harness that cannot fail on an injected fault is
// worthless — this exercises that failure directly.
void test_fault_evidence_matrix_perturbation(void) {
    // TRIADIC / spread 0 is a clean RGB permutation (out_r = in_b, out_g = in_r,
    // out_b = in_g); the red probe (255,0,0) has a golden out_r of ~0.
    const EdgeMixerMode mode = EdgeMixerMode::TRIADIC;
    const uint8_t spread = 0;

    // Perturbation: +4 units in the source's Q8.8 matrix granularity applied to
    // one coefficient. 4 Q8.8-LSB = 4 * 256 = 1024 in Q15.16 = 0.015625 in
    // normalised matrix units. Comfortably >= the 2-LSB floor the task mandates
    // and, against a 255-valued channel, shifts the output by ~4 8-bit LSB.
    const int perturbIndex = 0;                 // out_r from in_r
    const int32_t perturbQ16 = 4 * 256;         // >= 2 LSB, unambiguous

    // Locate the golden rows for this (mode,spread).
    int worstRestored = 0;
    int worstPerturbed = 0;

    const RefMatrix restored = refMatrixFor(mode, spread, -1, 0);
    const RefMatrix broken   = refMatrixFor(mode, spread, perturbIndex, perturbQ16);

    for (int i = 0; i < g_goldenCount; ++i) {
        const GoldenRow& row = g_golden[i];
        if (row.mode != static_cast<uint8_t>(mode) || row.spread != spread) continue;

        const CRGB in(row.in_r, row.in_g, row.in_b);

        const CRGB okOut = refApply(restored, in);
        const int okD = (std::max)({absDelta(okOut.r, row.out_r),
                                    absDelta(okOut.g, row.out_g),
                                    absDelta(okOut.b, row.out_b)});
        if (okD > worstRestored) worstRestored = okD;

        const CRGB badOut = refApply(broken, in);
        const int badD = (std::max)({absDelta(badOut.r, row.out_r),
                                     absDelta(badOut.g, row.out_g),
                                     absDelta(badOut.b, row.out_b)});
        if (badD > worstPerturbed) worstPerturbed = badD;
    }

    std::printf("[FAULT] restored max delta = %d LSB (GREEN <=1), perturbed max delta = %d LSB (RED >1)\n",
                worstRestored, worstPerturbed);
    std::fflush(stdout);

    // Restored matrix: parity holds (GREEN).
    TEST_ASSERT_LESS_OR_EQUAL_INT_MESSAGE(
        1, worstRestored, "restored matrix must satisfy the +/-1 LSB parity gate");

    // Perturbed matrix: parity breaks for at least one vector (RED). If this
    // does not exceed 1 LSB, the oracle is not exercising real data — fail loud.
    TEST_ASSERT_GREATER_THAN_INT_MESSAGE(
        1, worstPerturbed,
        "injected coefficient fault MUST break parity by > 1 LSB (fault-evidence)");
}

// The golden CSV artefact was written.
void test_golden_csv_written(void) {
    TEST_ASSERT_TRUE_MESSAGE(g_csvOk, "edgemixer_golden.csv could not be opened for writing");
    TEST_ASSERT_EQUAL_INT_MESSAGE(kMaxRows, g_csvRows,
                                  "golden CSV row count must equal modes*spreads*probes");
}

int main(int, char**) {
    generateGoldensAndCsv();

    UNITY_BEGIN();
    RUN_TEST(test_golden_csv_written);
    RUN_TEST(test_near_black_passthrough);
    RUN_TEST(test_parity_within_one_lsb);
    RUN_TEST(test_fault_evidence_matrix_perturbation);
    return UNITY_END();
}
