/**
 * @file FallbackControllerHtml.h
 * @brief Pre-compressed gzip of the K1 fallback controller HTML page.
 *
 * This header declares the PROGMEM byte array produced by the build helper.
 * The matching .cpp is generated by:
 *
 *     python3 firmware-v3/scripts/gen_fallback_html.py
 *
 * Source: docs/web/fallback_controller_source.html
 *
 * Serving pattern (ESPAsyncWebServer 3.x):
 *
 *   auto* resp = request->beginResponse(200, "text/html",
 *                                        FALLBACK_HTML_GZ, FALLBACK_HTML_GZ_LEN);
 *   resp->addHeader("Content-Encoding", "gzip");
 *   request->send(resp);
 *
 * Safari, Chrome, and Firefox all support gzip Content-Encoding for HTML.
 * The response body is served directly from flash; no SRAM copy is made.
 */

#pragma once

#include <stddef.h>
#include <stdint.h>

// PROGMEM is defined by the Arduino/ESP-IDF toolchain.  Include the Arduino
// header when not building for a native host (e.g. unit tests).
#ifndef NATIVE_BUILD
#include <Arduino.h>
#endif

#ifndef PROGMEM
#define PROGMEM
#endif

// Gzip-compressed HTML page.  Served with Content-Encoding: gzip.
// Declared extern; definition lives in FallbackControllerHtml.cpp (generated).
extern const uint8_t FALLBACK_HTML_GZ[] PROGMEM;
extern const size_t  FALLBACK_HTML_GZ_LEN;
