/**
 * @file StaticAssetRoutes.h
 * @brief Fallback controller and provisioning portal route registration.
 *
 * Serves the K1 fallback controller HTML (pre-compressed gzip PROGMEM) at
 * the root URL in STA mode and at /control in both modes.  The provisioning
 * portal is served at / in AP mode and at /provision in both modes.
 *
 * The gzip byte array is declared in FallbackControllerHtml.h and defined in
 * FallbackControllerHtml.cpp (generated by scripts/gen_fallback_html.py).
 * No LittleFS or external asset files are required.
 */

#pragma once

#include "HttpRouteRegistry.h"
#include "FallbackControllerHtml.h"

namespace lightwaveos {
namespace network {
namespace webserver {

/**
 * @brief Static asset route registrar
 */
class StaticAssetRoutes {
public:
    /**
     * @brief Register all static asset routes
     * @param registry Route registry
     */
    static void registerRoutes(HttpRouteRegistry& registry);
};

} // namespace webserver
} // namespace network
} // namespace lightwaveos

