/**
 * @file StaticAssetRoutes.cpp
 * @brief Static HTML asset routes — fallback controller and provisioning portal.
 *
 * Serves:
 *   AP mode:  GET /        → provisioning portal (PROVISIONING_HTML snprintf)
 *             GET /provision → provisioning portal
 *             GET /control  → fallback controller (gzip PROGMEM)
 *   STA mode: GET /        → fallback controller (gzip PROGMEM)
 *             GET /provision → provisioning portal
 *             GET /control  → fallback controller (gzip PROGMEM)
 *             onNotFound HTML GET → fallback controller (SPA-style fallback)
 *
 * The fallback controller HTML is stored pre-compressed in flash as a
 * gzip byte array (FallbackControllerHtml.cpp, generated by
 * firmware-v3/scripts/gen_fallback_html.py from
 * docs/web/fallback_controller_source.html).
 * Serving it requires a single beginResponse() + addHeader() — zero SRAM copy.
 */

#include "StaticAssetRoutes.h"
#include "FallbackControllerHtml.h"
#include "../ApiResponse.h"
#include "CaptivePortalProbes.h"
#include <WiFi.h>
#include <Arduino.h>
#include <cstdlib>
#ifndef NATIVE_BUILD
#include <esp_heap_caps.h>
#endif
#include "../../config/version.h"
#include "../../config/network_config.h"
#define LW_LOG_TAG "StaticRoutes"
#include "../../utils/Log.h"

namespace lightwaveos {
namespace network {
namespace webserver {

namespace {

constexpr size_t kProvisioningBufferSize = 6144;

/** Send the pre-compressed fallback controller page with Content-Encoding: gzip. */
static void sendFallbackController(AsyncWebServerRequest* request) {
    auto* resp = request->beginResponse(
        200, "text/html",
        FALLBACK_HTML_GZ, FALLBACK_HTML_GZ_LEN);
    resp->addHeader("Content-Encoding", "gzip");
    resp->addHeader("Cache-Control", "no-cache");
    request->send(resp);
}

char* getProvisioningBuffer() {
    static char* buffer = nullptr;
    if (buffer) {
        return buffer;
    }

#if !defined(NATIVE_BUILD) && defined(BOARD_HAS_PSRAM)
    buffer = static_cast<char*>(
        heap_caps_malloc(kProvisioningBufferSize, MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT));
#endif
#if !defined(NATIVE_BUILD)
    if (!buffer) {
        buffer = static_cast<char*>(
            heap_caps_malloc(kProvisioningBufferSize, MALLOC_CAP_8BIT));
    }
#else
    if (!buffer) {
        buffer = static_cast<char*>(std::malloc(kProvisioningBufferSize));
    }
#endif
    return buffer;
}

} // namespace

// ---------------------------------------------------------------------------
// HTML template  (provisioning only — raw string literal with snprintf placeholders)
// LAUNCHER_HTML removed: replaced by FALLBACK_HTML_GZ (gzip PROGMEM, see FallbackControllerHtml.h)
// ---------------------------------------------------------------------------

static const char PROVISIONING_HTML[] PROGMEM = R"rawhtml(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>LightwaveOS Setup</title>
<style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:#10141d;color:#edf1f7;
font-family:system-ui,-apple-system,sans-serif;display:flex;align-items:center;justify-content:center;padding:24px}
.wrap{width:100%%;max-width:420px}.brand{font-size:1.8rem;font-weight:700;color:#ffb84d;margin-bottom:8px}
p{color:#aab3c2;line-height:1.45;margin:0 0 22px}label{display:block;font-size:.86rem;color:#c8d0dc;margin:14px 0 6px}
input{width:100%%;height:46px;border:1px solid #30384a;background:#171d29;color:#fff;border-radius:8px;
padding:0 12px;font-size:1rem}button{width:100%%;height:48px;border:0;border-radius:8px;background:#ffb84d;
color:#10141d;font-size:1rem;font-weight:700;margin-top:18px}button:disabled{opacity:.6}
.msg{min-height:24px;margin-top:14px;color:#aab3c2}.ok{color:#6ee7a8}.err{color:#ff8f8f}
.foot{margin-top:28px;font-size:.76rem;color:#667085}
</style>
</head>
<body>
<main class="wrap">
<div class="brand">LightwaveOS</div>
<p>Connect this K1 to a WiFi network. The device will restart and join that network.</p>
<form id="form">
<label for="ssid">Network name</label>
<input id="ssid" name="ssid" autocomplete="off" maxlength="32" required/>
<label for="password">Password</label>
<input id="password" name="password" type="password" maxlength="64"/>
<button id="submit" type="submit">Save and restart</button>
</form>
<div id="msg" class="msg"></div>
<div class="foot">v%s &middot; %s.local</div>
</main>
<script>
const form=document.getElementById('form'),msg=document.getElementById('msg'),btn=document.getElementById('submit');
form.addEventListener('submit',async e=>{
 e.preventDefault();btn.disabled=true;msg.className='msg';msg.textContent='Saving...';
 const ssid=form.ssid.value.trim(),password=form.password.value;
 try{
  const r=await fetch('/api/v1/network/provision',{method:'POST',headers:{'Content-Type':'application/json'},
   body:JSON.stringify({ssid,password})});
  const j=await r.json();
  if(!r.ok||!j.success)throw new Error(j.error||'Provisioning failed');
  msg.className='msg ok';msg.textContent='Saved. Restarting now.';
 }catch(err){msg.className='msg err';msg.textContent=err.message;btn.disabled=false;}
});
</script>
</body>
</html>)rawhtml";

// ---------------------------------------------------------------------------
// Route registration
// ---------------------------------------------------------------------------

void StaticAssetRoutes::registerRoutes(HttpRouteRegistry& registry) {

    // ── Helper: serve provisioning page (used on /provision always; on / in AP mode) ─────
    auto serveProvisioningPage = [](AsyncWebServerRequest* request) {
        char* buf = getProvisioningBuffer();
        if (!buf) {
            request->send(HttpStatus::SERVICE_UNAVAILABLE,
                          "text/plain", "Provisioning unavailable");
            return;
        }
        snprintf(buf, kProvisioningBufferSize, PROVISIONING_HTML,
                 FIRMWARE_VERSION_STRING,
                 config::NetworkConfig::MDNS_HOSTNAME);
        request->send(200, "text/html", buf);
    };

    // ── GET / ────────────────────────────────────────────────────────────
    // Mode-aware root: AP → provisioning portal, STA → fallback controller.
    // Runtime WiFi.getMode() check honours dual-mode K1 (ab8ef0ae) — no
    // compile-time WIFI_AP_ONLY gating.
    registry.onGet("/", [serveProvisioningPage](AsyncWebServerRequest* request) {
        if (WiFi.getMode() == WIFI_MODE_AP) {
            serveProvisioningPage(request);
            return;
        }
        sendFallbackController(request);
    });

    // ── GET /provision ───────────────────────────────────────────────────
    // Available in both AP and STA modes; always shows the provisioning portal
    // so users can re-join a different WiFi network without serial access.
    registry.onGet("/provision", [serveProvisioningPage](AsyncWebServerRequest* request) {
        serveProvisioningPage(request);
    });

    // ── GET /control ─────────────────────────────────────────────────────
    // Explicit direct-URL for the fallback controller, available in both modes.
    // In AP mode the user can still reach it after connecting to the K1 AP.
    registry.onGet("/control", [](AsyncWebServerRequest* request) {
        sendFallbackController(request);
    });

    // ── GET /favicon.ico ─────────────────────────────────────────────────
    registry.onGet("/favicon.ico", [](AsyncWebServerRequest* request) {
        request->send(HttpStatus::NO_CONTENT);
    });

    // ── Captive-portal detection probes ──────────────────────────────────
    // Active only while serving as Access Point (runtime check). Mobile and
    // desktop OS detectors expect canonical "success" responses on these paths;
    // returning that would suppress the portal sheet. We deliberately return
    // captive-positive shapes (302 to root or non-canonical HTML with meta
    // refresh) so iOS / Android / macOS / Firefox / Windows auto-open the
    // provisioning UI. STA-mode operation returns 404 unchanged.
    auto registerCaptiveProbe = [&registry](const char* path) {
        registry.onGet(path, [path](AsyncWebServerRequest* request) {
            if (WiFi.getMode() == WIFI_MODE_AP) {
                const auto resp = captive_portal::responseForProbePath(path);
                if (resp.action == captive_portal::ProbeAction::RedirectToRoot) {
                    request->redirect(resp.location);
                    return;
                }
                if (resp.action == captive_portal::ProbeAction::BootstrapHtml) {
                    request->send(200, resp.contentType, resp.body);
                    return;
                }
            }
            request->send(HttpStatus::NOT_FOUND);
        });
    };
    registerCaptiveProbe("/generate_204");              // Android, Chromium
    registerCaptiveProbe("/hotspot-detect.html");       // iOS, iPadOS, macOS
    registerCaptiveProbe("/library/test/success.html"); // macOS alternate
    registerCaptiveProbe("/connectivity-check.html");   // Generic detector
    registerCaptiveProbe("/canonical.html");             // Firefox detectportal
    registerCaptiveProbe("/connecttest.txt");            // Windows 10+ NCSI
    registerCaptiveProbe("/ncsi.txt");                   // Legacy Windows NCSI
    registerCaptiveProbe("/redirect");                   // Windows NCSI follow-up

    // ── 404 / onNotFound ─────────────────────────────────────────────────
    registry.onNotFound([](AsyncWebServerRequest* request) {
        // CORS preflight — pass through for all routes
        if (request->method() == HTTP_OPTIONS) {
            request->send(HttpStatus::NO_CONTENT);
            return;
        }

        // API and WebSocket paths always get a structured JSON error
        String url = request->url();
        if (url.startsWith("/api") || url.startsWith("/ws")) {
            sendErrorResponse(request, HttpStatus::NOT_FOUND,
                              ErrorCodes::NOT_FOUND, "Endpoint not found");
            return;
        }

        // AP mode: captive-portal / browser-probe fallback — redirect to /
        if (WiFi.getMode() == WIFI_MODE_AP) {
            request->redirect("/");
            return;
        }

        // STA mode: for browser-initiated HTML navigation to an unknown path,
        // serve the fallback controller so direct URL-bar typing lands on the
        // controller rather than a bare 404. API clients get a 404 above.
        const String acceptHeader = request->header("Accept");
        if (acceptHeader.indexOf("text/html") >= 0) {
            sendFallbackController(request);
            return;
        }

        request->send(HttpStatus::NOT_FOUND, "text/plain", "Not found");
    });
}

} // namespace webserver
} // namespace network
} // namespace lightwaveos
