/**
 * @file GeneratedAiryCometEffect.h
 * @brief Generated by K1 Node Composer — Airy Comet (Fixed) preset
 *
 * This effect was generated from the Node Composer's "Airy Comet (Fixed)"
 * preset to verify the C++ export loop. The node graph:
 *   Band(0) → EMA(50ms) → MaxFollower → Gaussian(σ=0.25)
 *   Band(5) → EMA(40ms) → MaxFollower
 *   BeatStrength → Scale(0.7) + 0.3 → beat modulation
 *   SilentScale → silence gating
 *   geometry × normBass × beatMod × silScale → squared → HSV→RGB → LED output
 *
 * Centre-origin compliant. Dual-strip locked. No heap in render().
 */

#pragma once

#include "../../plugins/api/IEffect.h"
#include "../../plugins/api/EffectContext.h"
#include "../CoreEffects.h"
#include <FastLED.h>
#include <cmath>

namespace lightwaveos {
namespace effects {
namespace ieffect {

class GeneratedAiryCometEffect final : public plugins::IEffect {
public:
    // Stateful members (EMA smoothers + max followers)
    float m_bassSm = 0.0f;
    float m_trebleSm = 0.0f;
    float m_bassFollower = 0.15f;
    float m_trebleFollower = 0.15f;

    GeneratedAiryCometEffect() = default;
    ~GeneratedAiryCometEffect() override = default;

    bool init(plugins::EffectContext& ctx) override {
        (void)ctx;
        m_bassSm = 0.0f;
        m_trebleSm = 0.0f;
        m_bassFollower = 0.15f;
        m_trebleFollower = 0.15f;
        return true;
    }

    void render(plugins::EffectContext& ctx) override {
        const float rawDt = ctx.getSafeRawDeltaSeconds();

        // --- Sources ---
        const float rawBass = ctx.audio.available ? ctx.audio.getBand(0) : 0.0f;
        const float rawTreble = ctx.audio.available ? ctx.audio.getBand(5) : 0.0f;
        const float beatStr = ctx.audio.available ? ctx.audio.beatStrength() : 0.0f;
        const float silScale = ctx.audio.available ? ctx.audio.silentScale() : 1.0f;

        // --- EMA smooth (bass, tau=50ms) ---
        const float bassAlpha = 1.0f - expf(-rawDt / 0.0500f);
        m_bassSm += (rawBass - m_bassSm) * bassAlpha;

        // --- EMA smooth (treble, tau=40ms) ---
        const float trebleAlpha = 1.0f - expf(-rawDt / 0.0400f);
        m_trebleSm += (rawTreble - m_trebleSm) * trebleAlpha;

        // --- Max follower (bass: attack=58ms, decay=500ms, floor=0.04) ---
        const float atkAlpha = 1.0f - expf(-rawDt / 0.0580f);
        const float decAlpha = 1.0f - expf(-rawDt / 0.5000f);
        if (m_bassSm > m_bassFollower) {
            m_bassFollower += (m_bassSm - m_bassFollower) * atkAlpha;
        } else {
            m_bassFollower += (m_bassSm - m_bassFollower) * decAlpha;
        }
        if (m_bassFollower < 0.0400f) m_bassFollower = 0.0400f;
        const float normBass = fminf(1.0f, fmaxf(0.0f, m_bassSm / m_bassFollower));

        // --- Max follower (treble: same taus) ---
        if (m_trebleSm > m_trebleFollower) {
            m_trebleFollower += (m_trebleSm - m_trebleFollower) * atkAlpha;
        } else {
            m_trebleFollower += (m_trebleSm - m_trebleFollower) * decAlpha;
        }
        if (m_trebleFollower < 0.0400f) m_trebleFollower = 0.0400f;
        // const float normTreble = fminf(1.0f, fmaxf(0.0f, m_trebleSm / m_trebleFollower));

        // --- Gaussian geometry (sigma=0.25, centre-origin, half-strip) ---
        float geom[STRIP_LENGTH];
        {
            const float sigma2 = 0.125000f;  // 2 * 0.25 * 0.25
            for (int i = 0; i < STRIP_LENGTH; i++) {
                const float dist = static_cast<float>(i) / (STRIP_LENGTH - 1);
                geom[i] = normBass * expf(-(dist * dist) / fmaxf(sigma2, 0.0001f));
            }
        }

        // --- Multiply: geometry × normBass ---
        float bassGeom[STRIP_LENGTH];
        for (int i = 0; i < STRIP_LENGTH; i++) {
            bassGeom[i] = geom[i] * normBass;
        }

        // --- Beat modulation: 0.3 + 0.7 * beatStrength ---
        const float beatMod = 0.3f + beatStr * 0.7000f;

        // --- Multiply: bassGeom × beatMod ---
        float beatModulated[STRIP_LENGTH];
        for (int i = 0; i < STRIP_LENGTH; i++) {
            beatModulated[i] = bassGeom[i] * beatMod;
        }

        // --- Multiply: beatModulated × silScale ---
        float silenced[STRIP_LENGTH];
        for (int i = 0; i < STRIP_LENGTH; i++) {
            silenced[i] = beatModulated[i] * silScale;
        }

        // --- Power: squared for punch ---
        float squared[STRIP_LENGTH];
        for (int i = 0; i < STRIP_LENGTH; i++) {
            squared[i] = silenced[i] * silenced[i];
        }

        // --- HSV to RGB (hueOffset=0, hueSpread=48) ---
        CRGB colours[STRIP_LENGTH];
        {
            for (int i = 0; i < STRIP_LENGTH; i++) {
                const float progress = static_cast<float>(i) / (STRIP_LENGTH - 1);
                const uint8_t brightness = static_cast<uint8_t>(fminf(255.0f, fmaxf(0.0f, squared[i] * 255.0f)));
                const uint8_t hue = static_cast<uint8_t>(static_cast<int>(ctx.gHue + progress * 48.0f) & 0xFF);
                colours[i] = CHSV(hue, ctx.saturation, brightness);
            }
        }

        // --- Centre-origin LED output with trail persistence (fadeAmount=30) ---
        const uint8_t fadeScale = 225;  // 255 - 30
        for (uint16_t i = 0; i < ctx.ledCount; i++) {
            ctx.leds[i].nscale8(fadeScale);
        }
        for (int dist = 0; dist < STRIP_LENGTH; dist++) {
            SET_CENTER_PAIR(ctx, dist, colours[dist]);
        }
    }

    void cleanup() override {}

    const plugins::EffectMetadata& getMetadata() const override {
        static plugins::EffectMetadata meta{
            "Generated Airy Comet",
            "Node Composer export test — Airy Comet (Fixed) preset",
            plugins::EffectCategory::CUSTOM, 1
        };
        return meta;
    }

    uint8_t getParameterCount() const override { return 0; }
    const plugins::EffectParameter* getParameter(uint8_t) const override { return nullptr; }
    bool setParameter(const char*, float) override { return false; }
    float getParameter(const char*) const override { return 0.0f; }
};

} // namespace ieffect
} // namespace effects
} // namespace lightwaveos
