#pragma once
// ============================================================================
// PaletteLedData - Pre-computed palette colors for LED display
// ============================================================================
// Auto-generated by tools/palette_extractor.py
// Contains 9 representative colors per palette (75 palettes total)
// Colors sampled across visible range (skips black/dim endpoints)
// Colors are sorted by hue for visual cohesion (rainbow-like progression)
// Ensures all 9 LEDs display visible colors for every palette
// ============================================================================

#include <stdint.h>
#include <Arduino.h>

// Number of palettes
constexpr uint8_t PALETTE_LED_COUNT = 75;

// Number of colors per palette (for 9 LEDs)
constexpr uint8_t PALETTE_COLORS_PER_PALETTE = 9;

// PROGMEM array: paletteLedColors[paletteId][ledIndex][r/g/b]
// paletteId: 0-74 (75 palettes)
// ledIndex: 0-8 (9 LEDs)
// RGB: 0-255
// Colors are sorted by hue (0-360°) for visual cohesion
const uint8_t paletteLedColors[PALETTE_LED_COUNT][PALETTE_COLORS_PER_PALETTE][3] PROGMEM = {
    // Palette 0: Sunset_Real_gp
    {
        {120,   0,   0},  // LED 0 (brightness: 120)
        {202,  47,   0},  // LED 1 (brightness: 202)
        {226,  74,   3},  // LED 2 (brightness: 226)
        {  0,   0, 160},  // LED 3 (brightness: 160)
        {  8,   0, 143},  // LED 4 (brightness: 143)
        { 25,   0, 127},  // LED 5 (brightness: 127)
        { 68,   0, 113},  // LED 6 (brightness: 113)
        {111,   1,  89},  // LED 7 (brightness: 111)
        {163,  10,  30}  // LED 8 (brightness: 163)
    },
    // Palette 1: es_rivendell_15_gp
    {
        {154, 162,  88},  // LED 0 (brightness: 162)
        {129, 140,  71},  // LED 1 (brightness: 140)
        { 89, 102,  45},  // LED 2 (brightness: 102)
        { 53,  70,  21},  // LED 3 (brightness: 70)
        { 31,  53,  15},  // LED 4 (brightness: 53)
        { 13,  38,  10},  // LED 5 (brightness: 38)
        {  8,  30,   8},  // LED 6 (brightness: 30)
        {  3,  22,   5},  // LED 7 (brightness: 22)
        {  0,  14,   4}  // LED 8 (brightness: 14)
    },
    // Palette 2: es_ocean_breeze_036_gp
    {
        {  0,  99, 111},  // LED 0 (brightness: 111)
        {  0,  73,  82},  // LED 1 (brightness: 82)
        { 13, 106, 127},  // LED 2 (brightness: 127)
        { 25, 139, 169},  // LED 3 (brightness: 169)
        { 42, 133, 164},  // LED 4 (brightness: 164)
        { 73, 173, 217},  // LED 5 (brightness: 217)
        { 71, 160, 201},  // LED 6 (brightness: 201)
        { 84, 144, 178},  // LED 7 (brightness: 178)
        { 99, 185, 236}  // LED 8 (brightness: 236)
    },
    // Palette 3: rgi_15_gp
    {
        {  3,   0,  31},  // LED 0 (brightness: 31)
        {  5,   1,  35},  // LED 1 (brightness: 35)
        { 22,   3,  41},  // LED 2 (brightness: 41)
        { 41,   2,  34},  // LED 3 (brightness: 41)
        { 60,   4,  35},  // LED 4 (brightness: 60)
        { 55,   0,  15},  // LED 5 (brightness: 55)
        { 60,   1,  16},  // LED 6 (brightness: 60)
        {119,   7,  29},  // LED 7 (brightness: 119)
        {198,   1,   6}  // LED 8 (brightness: 198)
    },
    // Palette 4: retro2_16_gp
    {
        { 46,   6,   0},  // LED 0 (brightness: 46)
        { 63,  22,   0},  // LED 1 (brightness: 63)
        { 81,  38,   0},  // LED 2 (brightness: 81)
        { 99,  55,   0},  // LED 3 (brightness: 99)
        {117,  71,   0},  // LED 4 (brightness: 117)
        {135,  87,   0},  // LED 5 (brightness: 135)
        {152, 103,   0},  // LED 6 (brightness: 152)
        {170, 119,   0},  // LED 7 (brightness: 170)
        {188, 135,   0}  // LED 8 (brightness: 188)
    },
    // Palette 5: Analogous_1_gp
    {
        {255,   0,   0},  // LED 0 (brightness: 255)
        {  3,   0, 255},  // LED 1 (brightness: 255)
        { 12,   0, 255},  // LED 2 (brightness: 255)
        { 23,   0, 255},  // LED 3 (brightness: 255)
        { 45,   0, 255},  // LED 4 (brightness: 255)
        { 67,   0, 255},  // LED 5 (brightness: 255)
        {104,   0, 150},  // LED 6 (brightness: 150)
        {142,   0,  45},  // LED 7 (brightness: 142)
        {198,   0,  22}  // LED 8 (brightness: 198)
    },
    // Palette 6: es_pinksplash_08_gp
    {
        {125,   5, 255},  // LED 0 (brightness: 255)
        {144,   3, 201},  // LED 1 (brightness: 201)
        {163,   2, 140},  // LED 2 (brightness: 163)
        {158,   1, 112},  // LED 3 (brightness: 158)
        {158,   1, 112},  // LED 4 (brightness: 158)
        {203,  89, 151},  // LED 5 (brightness: 203)
        {180,   1,  79},  // LED 6 (brightness: 180)
        {223,  93, 115},  // LED 7 (brightness: 223)
        {197,   0,  21}  // LED 8 (brightness: 197)
    },
    // Palette 7: Coral_reef_gp
    {
        { 13, 212, 209},  // LED 0 (brightness: 212)
        {  7, 175, 177},  // LED 1 (brightness: 177)
        {  2, 142, 147},  // LED 2 (brightness: 147)
        {  0, 111, 120},  // LED 3 (brightness: 120)
        {  8,  89, 133},  // LED 4 (brightness: 133)
        {  3,  66, 107},  // LED 5 (brightness: 107)
        {  2,  55,  95},  // LED 6 (brightness: 95)
        {  1,  44,  83},  // LED 7 (brightness: 83)
        {  0,  33,  71}  // LED 8 (brightness: 71)
    },
    // Palette 8: es_ocean_breeze_068_gp
    {
        { 89, 161, 158},  // LED 0 (brightness: 161)
        { 40, 136, 156},  // LED 1 (brightness: 156)
        {  0,  75,  96},  // LED 2 (brightness: 96)
        { 12, 139, 175},  // LED 3 (brightness: 175)
        {  5, 108, 144},  // LED 4 (brightness: 144)
        {  0,  89, 121},  // LED 5 (brightness: 121)
        {  9, 113, 157},  // LED 6 (brightness: 157)
        {  4,  87, 136},  // LED 7 (brightness: 136)
        {  0,  63, 117}  // LED 8 (brightness: 117)
    },
    // Palette 9: es_pinksplash_07_gp
    {
        {229,   0,   0},  // LED 0 (brightness: 229)
        {191,  56, 191},  // LED 1 (brightness: 191)
        {255,   3, 228},  // LED 2 (brightness: 255)
        {255,   3, 211},  // LED 3 (brightness: 255)
        {246,   2,  75},  // LED 4 (brightness: 246)
        {244,   2,  71},  // LED 5 (brightness: 244)
        {239,   1,  36},  // LED 6 (brightness: 239)
        {236,   1,  31},  // LED 7 (brightness: 236)
        {232,   0,   4}  // LED 8 (brightness: 232)
    },
    // Palette 10: es_vintage_01_gp
    {
        { 42,   3,   1},  // LED 0 (brightness: 42)
        { 69,   7,   2},  // LED 1 (brightness: 69)
        {166,  69,   5},  // LED 2 (brightness: 166)
        {255, 125,   9},  // LED 3 (brightness: 255)
        {183, 119,   4},  // LED 4 (brightness: 183)
        { 54,  49,   0},  // LED 5 (brightness: 54)
        { 97, 105,   1},  // LED 6 (brightness: 105)
        { 16,   0,   1},  // LED 7 (brightness: 16)
        { 16,   0,   1}  // LED 8 (brightness: 16)
    },
    // Palette 11: departure_gp
    {
        { 23,   7,   0},  // LED 0 (brightness: 23)
        {103,  51,   6},  // LED 1 (brightness: 103)
        {208, 133,  61},  // LED 2 (brightness: 208)
        {240, 212, 179},  // LED 3 (brightness: 240)
        {  0, 226,   0},  // LED 4 (brightness: 226)
        {  0,  97,   0},  // LED 5 (brightness: 97)
        {  0,  55,   0},  // LED 6 (brightness: 55)
        {  0,  55,   0},  // LED 7 (brightness: 55)
        { 14, 255,  16}  // LED 8 (brightness: 255)
    },
    // Palette 12: es_landscape_64_gp
    {
        { 66, 195,   0},  // LED 0 (brightness: 195)
        { 32, 144,   1},  // LED 1 (brightness: 144)
        { 10,  88,   1},  // LED 2 (brightness: 88)
        {  1,  25,   0},  // LED 3 (brightness: 25)
        {147, 190, 225},  // LED 4 (brightness: 225)
        { 94, 154, 239},  // LED 5 (brightness: 239)
        { 41, 115, 255},  // LED 6 (brightness: 255)
        { 18,  74, 241},  // LED 7 (brightness: 241)
        {  0,  36, 192}  // LED 8 (brightness: 192)
    },
    // Palette 13: es_landscape_33_gp
    {
        {147,  50,   0},  // LED 0 (brightness: 147)
        {106,  40,   0},  // LED 1 (brightness: 106)
        {171,  68,   0},  // LED 2 (brightness: 171)
        { 65,  30,   0},  // LED 3 (brightness: 65)
        {188,  89,   0},  // LED 4 (brightness: 188)
        {204, 111,   0},  // LED 5 (brightness: 204)
        {220, 133,   0},  // LED 6 (brightness: 220)
        { 32,  23,   0},  // LED 7 (brightness: 32)
        { 25, 159,  70}  // LED 8 (brightness: 159)
    },
    // Palette 14: rainbowsherbet_gp
    {
        {178, 128, 128},  // LED 0 (brightness: 178)
        {255,  31,  16},  // LED 1 (brightness: 255)
        {255,  31,   2},  // LED 2 (brightness: 255)
        {255,  53,  11},  // LED 3 (brightness: 255)
        { 91, 178,  75},  // LED 4 (brightness: 178)
        { 72, 255,  43},  // LED 5 (brightness: 255)
        { 45, 255,  22},  // LED 6 (brightness: 255)
        {255,  62,  89},  // LED 7 (brightness: 255)
        {255,  14,  35}  // LED 8 (brightness: 255)
    },
    // Palette 15: gr65_hult_gp
    {
        {  0, 124, 109},  // LED 0 (brightness: 124)
        {  0, 124, 109},  // LED 1 (brightness: 124)
        {  0, 114, 125},  // LED 2 (brightness: 125)
        {  2,  94, 159},  // LED 3 (brightness: 159)
        { 19,  69, 203},  // LED 4 (brightness: 203)
        {108,  34, 224},  // LED 5 (brightness: 224)
        {198,  13, 232},  // LED 6 (brightness: 232)
        {186,  44, 190},  // LED 7 (brightness: 190)
        {178,  78, 178}  // LED 8 (brightness: 178)
    },
    // Palette 16: gr64_hult_gp
    {
        {107, 119,   0},  // LED 0 (brightness: 119)
        { 43,  74,   6},  // LED 1 (brightness: 74)
        { 37,  79,  11},  // LED 2 (brightness: 79)
        {  4,  85,  59},  // LED 3 (brightness: 85)
        {  0,  55,  45},  // LED 4 (brightness: 55)
        {  0,  68,  56},  // LED 5 (brightness: 68)
        {  0,  94,  80},  // LED 6 (brightness: 94)
        {  0, 109,  94},  // LED 7 (brightness: 109)
        {  0, 124, 109}  // LED 8 (brightness: 124)
    },
    // Palette 17: GMT_drywet_gp
    {
        { 47,  30,   0},  // LED 0 (brightness: 47)
        {177, 117,   8},  // LED 1 (brightness: 177)
        {166, 197,  14},  // LED 2 (brightness: 197)
        { 61, 246,  79},  // LED 3 (brightness: 246)
        {  1, 220, 207},  // LED 4 (brightness: 220)
        {  0,  90, 212},  // LED 5 (brightness: 212)
        {  0,   6,  33},  // LED 6 (brightness: 33)
        {  0,  23, 162},  // LED 7 (brightness: 162)
        {  0,   1,  91}  // LED 8 (brightness: 91)
    },
    // Palette 18: ib_jul01_gp
    {
        {194,   0,   0},  // LED 0 (brightness: 194)
        {113,   0,   0},  // LED 1 (brightness: 113)
        {133,   8,   3},  // LED 2 (brightness: 133)
        { 71,  16,   7},  // LED 3 (brightness: 71)
        {102,  32,   4},  // LED 4 (brightness: 102)
        { 89,  70,   6},  // LED 5 (brightness: 89)
        { 70, 112,  10},  // LED 6 (brightness: 112)
        { 44, 132,  15},  // LED 7 (brightness: 132)
        {  0,  31,  18}  // LED 8 (brightness: 31)
    },
    // Palette 19: es_vintage_57_gp
    {
        { 18,   1,   0},  // LED 0 (brightness: 18)
        { 43,  14,   0},  // LED 1 (brightness: 43)
        { 68,  28,   0},  // LED 2 (brightness: 68)
        {119,  80,   2},  // LED 3 (brightness: 119)
        {168, 135,   3},  // LED 4 (brightness: 168)
        {139, 115,   3},  // LED 5 (brightness: 139)
        {108,  96,   2},  // LED 6 (brightness: 108)
        { 77,  77,   1},  // LED 7 (brightness: 77)
        { 46,  57,   1}  // LED 8 (brightness: 57)
    },
    // Palette 20: ib15_gp
    {
        {202,  21,  17},  // LED 0 (brightness: 202)
        {163,  81,  79},  // LED 1 (brightness: 163)
        {237,  61,  14},  // LED 2 (brightness: 237)
        {111,  83, 156},  // LED 3 (brightness: 156)
        { 58,  24,  97},  // LED 4 (brightness: 97)
        { 85,  23,  77},  // LED 5 (brightness: 85)
        {136,  82, 118},  // LED 6 (brightness: 136)
        {113,  21,  58},  // LED 7 (brightness: 113)
        {141,  20,  39}  // LED 8 (brightness: 141)
    },
    // Palette 21: Fuschia_7_gp
    {
        { 42,   1, 154},  // LED 0 (brightness: 154)
        { 71,   1, 129},  // LED 1 (brightness: 129)
        {137,   8, 190},  // LED 2 (brightness: 190)
        {101,   1, 104},  // LED 3 (brightness: 104)
        {153,   5, 153},  // LED 4 (brightness: 153)
        {165,   4, 116},  // LED 5 (brightness: 165)
        {145,   1,  84},  // LED 6 (brightness: 145)
        {178,   4,  89},  // LED 7 (brightness: 178)
        {190,   2,  65}  // LED 8 (brightness: 190)
    },
    // Palette 22: es_emerald_dragon_08_gp
    {
        { 96, 255,   0},  // LED 0 (brightness: 255)
        { 85, 228,   0},  // LED 1 (brightness: 228)
        { 74, 201,   0},  // LED 2 (brightness: 201)
        { 63, 175,   0},  // LED 3 (brightness: 175)
        { 51, 147,   0},  // LED 4 (brightness: 147)
        { 41, 121,   0},  // LED 5 (brightness: 121)
        { 31,  95,   0},  // LED 6 (brightness: 95)
        { 22,  69,   0},  // LED 7 (brightness: 69)
        { 12,  43,   0}  // LED 8 (brightness: 43)
    },
    // Palette 23: lava_gp
    {
        { 18,   0,   0},  // LED 0 (brightness: 18)
        { 63,   0,   0},  // LED 1 (brightness: 63)
        {111,   0,   0},  // LED 2 (brightness: 111)
        {176,  17,   0},  // LED 3 (brightness: 176)
        {211,  42,   0},  // LED 4 (brightness: 211)
        {248,  74,   1},  // LED 5 (brightness: 248)
        {255, 132,   1},  // LED 6 (brightness: 255)
        {255, 206,   1},  // LED 7 (brightness: 255)
        {191, 191,  40}  // LED 8 (brightness: 191)
    },
    // Palette 24: fire_gp
    {
        {180,  22,   0},  // LED 0 (brightness: 180)
        {130,  16,   0},  // LED 1 (brightness: 130)
        { 80,  10,   0},  // LED 2 (brightness: 80)
        { 32,   5,   0},  // LED 3 (brightness: 32)
        {201,  50,   0},  // LED 4 (brightness: 201)
        {213,  83,   1},  // LED 5 (brightness: 213)
        {230, 136,   4},  // LED 6 (brightness: 230)
        {251, 218,   8},  // LED 7 (brightness: 251)
        {191, 191,  98}  // LED 8 (brightness: 191)
    },
    // Palette 25: Colorfull_gp
    {
        {177, 178,  81},  // LED 0 (brightness: 178)
        { 89,  97,  45},  // LED 1 (brightness: 97)
        { 55, 150,  30},  // LED 2 (brightness: 150)
        { 28, 126,  13},  // LED 3 (brightness: 126)
        {  8,  88,   3},  // LED 4 (brightness: 88)
        {122, 205, 148},  // LED 5 (brightness: 205)
        { 62, 172, 167},  // LED 6 (brightness: 172)
        { 29, 148, 181},  // LED 7 (brightness: 181)
        {  9, 123, 183}  // LED 8 (brightness: 183)
    },
    // Palette 26: Magenta_Evening_gp
    {
        { 49,   3,  36},  // LED 0 (brightness: 49)
        { 65,   3,  38},  // LED 1 (brightness: 65)
        { 81,   2,  40},  // LED 2 (brightness: 81)
        { 98,   2,  44},  // LED 3 (brightness: 98)
        {114,   1,  47},  // LED 4 (brightness: 114)
        {136,   6,  49},  // LED 5 (brightness: 136)
        {175,   0,  57},  // LED 6 (brightness: 175)
        {214,   1,  63},  // LED 7 (brightness: 214)
        { 78,  21,  37}  // LED 8 (brightness: 78)
    },
    // Palette 27: Pink_Purple_gp
    {
        { 88, 152, 225},  // LED 0 (brightness: 225)
        {145, 125, 228},  // LED 1 (brightness: 228)
        { 46,  24,  96},  // LED 2 (brightness: 96)
        {115,  55, 194},  // LED 3 (brightness: 194)
        { 18,   1,  40},  // LED 4 (brightness: 40)
        { 27,   1,  47},  // LED 5 (brightness: 47)
        {135,  37, 162},  // LED 6 (brightness: 162)
        {147,  28, 145},  // LED 7 (brightness: 147)
        {158,  21, 129}  // LED 8 (brightness: 158)
    },
    // Palette 28: es_autumn_19_gp
    {
        { 26,   0,   0},  // LED 0 (brightness: 26)
        { 17,   0,   0},  // LED 1 (brightness: 17)
        { 50,   1,   0},  // LED 2 (brightness: 50)
        { 38,   1,   0},  // LED 3 (brightness: 38)
        { 73,   5,   0},  // LED 4 (brightness: 73)
        { 85,   6,   0},  // LED 5 (brightness: 85)
        {122,  37,   5},  // LED 6 (brightness: 122)
        {141,  91,  13},  // LED 7 (brightness: 141)
        {139, 136,  19}  // LED 8 (brightness: 139)
    },
    // Palette 29: BlacK_Blue_Magenta_White_gp
    {
        {  0,   0,  45},  // LED 0 (brightness: 45)
        {  0,   0, 150},  // LED 1 (brightness: 150)
        {  0,   0, 255},  // LED 2 (brightness: 255)
        { 20,   0, 255},  // LED 3 (brightness: 255)
        { 42,   0, 255},  // LED 4 (brightness: 255)
        {146,   0, 255},  // LED 5 (brightness: 255)
        {250,   0, 255},  // LED 6 (brightness: 255)
        {255,   8, 255},  // LED 7 (brightness: 255)
        {255,  18, 255}  // LED 8 (brightness: 255)
    },
    // Palette 30: BlacK_Magenta_Red_gp
    {
        {255,   0,   0},  // LED 0 (brightness: 255)
        { 42,   0,  45},  // LED 1 (brightness: 45)
        {121,   0, 123},  // LED 2 (brightness: 123)
        {201,   0, 202},  // LED 3 (brightness: 202)
        {255,   0, 228},  // LED 4 (brightness: 255)
        {255,   0, 150},  // LED 5 (brightness: 255)
        {255,   0,  71},  // LED 6 (brightness: 255)
        {255,   0,  33},  // LED 7 (brightness: 255)
        {255,   0,  16}  // LED 8 (brightness: 255)
    },
    // Palette 31: BlacK_Red_Magenta_Yellow_gp
    {
        { 42,   0,   0},  // LED 0 (brightness: 42)
        {173,   0,   0},  // LED 1 (brightness: 173)
        {255, 127,  14},  // LED 2 (brightness: 255)
        {255, 255,   0},  // LED 3 (brightness: 255)
        {255,   2, 231},  // LED 4 (brightness: 255)
        {255,   0, 147},  // LED 5 (brightness: 255)
        {255,  22,  94},  // LED 6 (brightness: 255)
        {255,   0,  38},  // LED 7 (brightness: 255)
        {255,   0,  11}  // LED 8 (brightness: 255)
    },
    // Palette 32: Blue_Cyan_Yellow_gp
    {
        {255, 255,   0},  // LED 0 (brightness: 255)
        {148, 255,  10},  // LED 1 (brightness: 255)
        { 27, 255,  31},  // LED 2 (brightness: 255)
        { 10, 255, 150},  // LED 3 (brightness: 255)
        {  0, 255, 255},  // LED 4 (brightness: 255)
        {  0, 155, 255},  // LED 5 (brightness: 255)
        {  0,  55, 255},  // LED 6 (brightness: 255)
        {  0,  27, 255},  // LED 7 (brightness: 255)
        {  0,   0, 255}  // LED 8 (brightness: 255)
    },
    // Palette 33: Crameri_Vik_gp
    {
        {115,  48,   0},  // LED 0 (brightness: 115)
        {156, 101,   7},  // LED 1 (brightness: 156)
        {197, 153,  67},  // LED 2 (brightness: 197)
        {224, 212, 180},  // LED 3 (brightness: 224)
        {193, 221, 235},  // LED 4 (brightness: 235)
        { 54, 143, 190},  // LED 5 (brightness: 190)
        {146, 195, 221},  // LED 6 (brightness: 221)
        {  4,  87, 145},  // LED 7 (brightness: 145)
        {  1,  42, 114}  // LED 8 (brightness: 114)
    },
    // Palette 34: Crameri_Tokyo_gp
    {
        {144, 147, 134},  // LED 0 (brightness: 147)
        {176, 240, 158},  // LED 1 (brightness: 240)
        {147, 176, 139},  // LED 2 (brightness: 176)
        {155, 205, 146},  // LED 3 (brightness: 205)
        { 53,  14,  71},  // LED 4 (brightness: 71)
        { 95,  33,  94},  // LED 5 (brightness: 95)
        {125,  60, 110},  // LED 6 (brightness: 125)
        {141,  93, 122},  // LED 7 (brightness: 141)
        {144, 121, 130}  // LED 8 (brightness: 144)
    },
    // Palette 35: Crameri_Roma_gp
    {
        {153,  65,   7},  // LED 0 (brightness: 153)
        {190, 125,  17},  // LED 1 (brightness: 190)
        {217, 189,  54},  // LED 2 (brightness: 217)
        {230, 228, 124},  // LED 3 (brightness: 230)
        {197, 240, 188},  // LED 4 (brightness: 240)
        {125, 222, 220},  // LED 5 (brightness: 222)
        { 60, 176, 219},  // LED 6 (brightness: 219)
        { 39, 122, 201},  // LED 7 (brightness: 201)
        { 22,  70, 185}  // LED 8 (brightness: 185)
    },
    // Palette 36: Crameri_Oleron_gp
    {
        {178, 158, 128},  // LED 0 (brightness: 178)
        {219, 178, 109},  // LED 1 (brightness: 219)
        {162, 137,  43},  // LED 2 (brightness: 162)
        { 66,  97,   6},  // LED 3 (brightness: 97)
        {115, 155, 126},  // LED 4 (brightness: 155)
        {127, 139, 172},  // LED 5 (brightness: 172)
        {136, 153, 218},  // LED 6 (brightness: 218)
        { 42,  59, 125},  // LED 7 (brightness: 125)
        { 87, 104, 170}  // LED 8 (brightness: 170)
    },
    // Palette 37: Crameri_Lisbon_gp
    {
        {117, 108,  58},  // LED 0 (brightness: 117)
        {173, 163,  98},  // LED 1 (brightness: 173)
        {229, 224, 165},  // LED 2 (brightness: 229)
        { 50,  49,  33},  // LED 3 (brightness: 50)
        { 16,  28,  38},  // LED 4 (brightness: 38)
        { 42,  92, 144},  // LED 5 (brightness: 144)
        { 15,  47,  81},  // LED 6 (brightness: 81)
        {105, 144, 196},  // LED 7 (brightness: 196)
        {181, 196, 236}  // LED 8 (brightness: 236)
    },
    // Palette 38: Crameri_LaJolla_gp
    {
        {201,  66,  59},  // LED 0 (brightness: 201)
        {151,  54,  47},  // LED 1 (brightness: 151)
        {243,  85,  62},  // LED 2 (brightness: 243)
        {103,  44,  29},  // LED 3 (brightness: 103)
        {250, 120,  60},  // LED 4 (brightness: 250)
        {255, 158,  59},  // LED 5 (brightness: 255)
        { 54,  34,   8},  // LED 6 (brightness: 54)
        {255, 193,  66},  // LED 7 (brightness: 255)
        {255, 227,  85}  // LED 8 (brightness: 255)
    },
    // Palette 39: Crameri_Hawaii_gp
    {
        {167,  81,  43},  // LED 0 (brightness: 167)
        {170, 118,  18},  // LED 1 (brightness: 170)
        {165, 158,  14},  // LED 2 (brightness: 165)
        {143, 196,  47},  // LED 3 (brightness: 196)
        {106, 223, 115},  // LED 4 (brightness: 223)
        { 79, 239, 186},  // LED 5 (brightness: 239)
        { 79, 174, 173},  // LED 6 (brightness: 174)
        {157,  13, 101},  // LED 7 (brightness: 157)
        {164,  46,  70}  // LED 8 (brightness: 164)
    },
    // Palette 40: Crameri_Devon_gp
    {
        { 32,  94, 176},  // LED 0 (brightness: 176)
        { 28,  76, 147},  // LED 1 (brightness: 147)
        { 56, 111, 204},  // LED 2 (brightness: 204)
        { 86, 125, 227},  // LED 3 (brightness: 227)
        { 31,  55, 122},  // LED 4 (brightness: 122)
        {127, 140, 240},  // LED 5 (brightness: 240)
        { 37,  35, 100},  // LED 6 (brightness: 100)
        {112, 109, 172},  // LED 7 (brightness: 172)
        {129, 123, 177}  // LED 8 (brightness: 177)
    },
    // Palette 41: Crameri_Cork_gp
    {
        { 66, 107,  11},  // LED 0 (brightness: 107)
        { 67, 154,  64},  // LED 1 (brightness: 154)
        {118, 188, 123},  // LED 2 (brightness: 188)
        {195, 223, 201},  // LED 3 (brightness: 223)
        {181, 192, 198},  // LED 4 (brightness: 198)
        {169, 194, 218},  // LED 5 (brightness: 218)
        { 98, 142, 188},  // LED 6 (brightness: 188)
        { 42,  94, 155},  // LED 7 (brightness: 155)
        { 35,  45, 112}  // LED 8 (brightness: 112)
    },
    // Palette 42: Crameri_Broc_gp
    {
        {180, 180, 106},  // LED 0 (brightness: 180)
        {124, 124,  57},  // LED 1 (brightness: 124)
        { 69,  69,  14},  // LED 2 (brightness: 69)
        {223, 224, 194},  // LED 3 (brightness: 224)
        {187, 195, 199},  // LED 4 (brightness: 199)
        {100, 143, 189},  // LED 5 (brightness: 189)
        {172, 195, 220},  // LED 6 (brightness: 220)
        { 43,  95, 156},  // LED 7 (brightness: 156)
        { 35,  45, 112}  // LED 8 (brightness: 112)
    },
    // Palette 43: Crameri_Berlin_gp
    {
        {237, 133, 124},  // LED 0 (brightness: 237)
        {180,  78,  58},  // LED 1 (brightness: 180)
        { 52,  15,   4},  // LED 2 (brightness: 52)
        {117,  36,  11},  // LED 3 (brightness: 117)
        { 15,  46,  61},  // LED 4 (brightness: 61)
        { 21,  93, 129},  // LED 5 (brightness: 129)
        { 43, 141, 197},  // LED 6 (brightness: 197)
        { 72, 118, 178},  // LED 7 (brightness: 178)
        { 20,  17,  20}  // LED 8 (brightness: 20)
    },
    // Palette 44: Crameri_Bamako_gp
    {
        {178, 155,  72},  // LED 0 (brightness: 178)
        {228, 197,  47},  // LED 1 (brightness: 228)
        {179, 163,   8},  // LED 2 (brightness: 179)
        {132, 143,   3},  // LED 3 (brightness: 143)
        { 99, 133,   8},  // LED 4 (brightness: 133)
        { 69, 119,  24},  // LED 5 (brightness: 119)
        { 43, 102,  43},  // LED 6 (brightness: 102)
        { 20,  88,  59},  // LED 7 (brightness: 88)
        {  3,  73,  74}  // LED 8 (brightness: 74)
    },
    // Palette 45: Crameri_Acton_gp
    {
        { 60,  42,  98},  // LED 0 (brightness: 98)
        { 88,  62, 119},  // LED 1 (brightness: 119)
        {119,  79, 136},  // LED 2 (brightness: 136)
        {154,  89, 146},  // LED 3 (brightness: 154)
        {218, 175, 207},  // LED 4 (brightness: 218)
        {187,  91, 150},  // LED 5 (brightness: 187)
        {219, 150, 192},  // LED 6 (brightness: 219)
        {220, 127, 176},  // LED 7 (brightness: 220)
        {212, 105, 161}  // LED 8 (brightness: 212)
    },
    // Palette 46: Crameri_Batlow_gp
    {
        {178, 114, 100},  // LED 0 (brightness: 178)
        {250, 152,  79},  // LED 1 (brightness: 250)
        {197, 145,  38},  // LED 2 (brightness: 197)
        {136, 136,  39},  // LED 3 (brightness: 136)
        { 80, 122,  66},  // LED 4 (brightness: 122)
        { 36, 102,  93},  // LED 5 (brightness: 102)
        {  8,  73, 104},  // LED 6 (brightness: 104)
        {  4,  41,  96},  // LED 7 (brightness: 96)
        {178, 128, 149}  // LED 8 (brightness: 178)
    },
    // Palette 47: Crameri_Bilbao_gp
    {
        {141,  42,  42},  // LED 0 (brightness: 141)
        {160,  69,  63},  // LED 1 (brightness: 160)
        {173,  97,  78},  // LED 2 (brightness: 173)
        {178, 123,  87},  // LED 3 (brightness: 178)
        {182, 147,  95},  // LED 4 (brightness: 182)
        {187, 168, 117},  // LED 5 (brightness: 187)
        {194, 185, 147},  // LED 6 (brightness: 194)
        {200, 197, 184},  // LED 7 (brightness: 200)
        {110,  13,  15}  // LED 8 (brightness: 110)
    },
    // Palette 48: Crameri_Buda_gp
    {
        {219, 125, 117},  // LED 0 (brightness: 219)
        {225, 154, 107},  // LED 1 (brightness: 225)
        {230, 184,  97},  // LED 2 (brightness: 230)
        {237, 214,  86},  // LED 3 (brightness: 237)
        {187, 186,  91},  // LED 4 (brightness: 187)
        {189,  10, 173},  // LED 5 (brightness: 189)
        {197,  36, 157},  // LED 6 (brightness: 197)
        {204,  67, 141},  // LED 7 (brightness: 204)
        {212,  97, 129}  // LED 8 (brightness: 212)
    },
    // Palette 49: Crameri_Davos_gp
    {
        {224, 224, 153},  // LED 0 (brightness: 224)
        {191, 203, 157},  // LED 1 (brightness: 203)
        {159, 182, 169},  // LED 2 (brightness: 182)
        {125, 162, 184},  // LED 3 (brightness: 184)
        { 95, 143, 198},  // LED 4 (brightness: 198)
        { 38, 103, 186},  // LED 5 (brightness: 186)
        { 26,  77, 148},  // LED 6 (brightness: 148)
        { 64, 124, 209},  // LED 7 (brightness: 209)
        { 34,  42, 108}  // LED 8 (brightness: 108)
    },
    // Palette 50: Crameri_GrayC_gp
    {
        {167, 167, 167},  // LED 0 (brightness: 167)
        {146, 146, 146},  // LED 1 (brightness: 146)
        {126, 126, 126},  // LED 2 (brightness: 126)
        {108, 108, 108},  // LED 3 (brightness: 108)
        { 89,  89,  89},  // LED 4 (brightness: 89)
        { 70,  70,  70},  // LED 5 (brightness: 70)
        { 53,  53,  53},  // LED 6 (brightness: 53)
        { 36,  36,  36},  // LED 7 (brightness: 36)
        { 20,  20,  20}  // LED 8 (brightness: 20)
    },
    // Palette 51: Crameri_Imola_gp
    {
        {230, 255,  75},  // LED 0 (brightness: 255)
        {170, 231,  88},  // LED 1 (brightness: 231)
        {133, 199, 103},  // LED 2 (brightness: 199)
        {101, 166, 117},  // LED 3 (brightness: 166)
        { 74, 139, 131},  // LED 4 (brightness: 139)
        { 52, 117, 150},  // LED 5 (brightness: 150)
        { 36,  97, 168},  // LED 6 (brightness: 168)
        { 24,  75, 183},  // LED 7 (brightness: 183)
        { 19,  55, 192}  // LED 8 (brightness: 192)
    },
    // Palette 52: Crameri_LaPaz_gp
    {
        {239, 186, 142},  // LED 0 (brightness: 239)
        {191, 172, 135},  // LED 1 (brightness: 191)
        {147, 165, 147},  // LED 2 (brightness: 165)
        {104, 157, 165},  // LED 3 (brightness: 165)
        { 65, 143, 178},  // LED 4 (brightness: 178)
        { 41, 117, 177},  // LED 5 (brightness: 177)
        { 28,  89, 167},  // LED 6 (brightness: 167)
        { 23,  59, 153},  // LED 7 (brightness: 153)
        { 22,  27, 132}  // LED 8 (brightness: 132)
    },
    // Palette 53: Crameri_Nuuk_gp
    {
        {197, 196, 126},  // LED 0 (brightness: 197)
        {215, 214, 118},  // LED 1 (brightness: 215)
        {172, 172,  97},  // LED 2 (brightness: 172)
        {180, 181, 139},  // LED 3 (brightness: 181)
        {158, 166, 147},  // LED 4 (brightness: 166)
        {125, 146, 146},  // LED 5 (brightness: 146)
        { 84, 126, 141},  // LED 6 (brightness: 141)
        { 46, 108, 139},  // LED 7 (brightness: 139)
        { 12,  96, 147}  // LED 8 (brightness: 147)
    },
    // Palette 54: Crameri_Oslo_gp
    {
        { 10,  60, 106},  // LED 0 (brightness: 106)
        { 20,  83, 151},  // LED 1 (brightness: 151)
        {  7,  36,  68},  // LED 2 (brightness: 68)
        { 38, 106, 196},  // LED 3 (brightness: 196)
        {140, 168, 208},  // LED 4 (brightness: 208)
        { 72, 126, 212},  // LED 5 (brightness: 212)
        {177, 187, 203},  // LED 6 (brightness: 203)
        {107, 147, 215},  // LED 7 (brightness: 215)
        {  6,  15,  31}  // LED 8 (brightness: 31)
    },
    // Palette 55: Crameri_Tofino_gp
    {
        {172, 215, 119},  // LED 0 (brightness: 215)
        { 84, 166,  77},  // LED 1 (brightness: 166)
        { 43, 111,  47},  // LED 2 (brightness: 111)
        { 20,  49,  25},  // LED 3 (brightness: 49)
        { 13,  24,  30},  // LED 4 (brightness: 30)
        { 22,  40,  75},  // LED 5 (brightness: 75)
        { 46,  80, 148},  // LED 6 (brightness: 148)
        { 94, 129, 213},  // LED 7 (brightness: 213)
        {120, 127, 172}  // LED 8 (brightness: 172)
    },
    // Palette 56: Crameri_Turku_gp
    {
        { 23,  23,  23},  // LED 0 (brightness: 23)
        {178, 119, 116},  // LED 1 (brightness: 178)
        {239, 159, 135},  // LED 2 (brightness: 239)
        {210, 154, 114},  // LED 3 (brightness: 210)
        {175, 146,  98},  // LED 4 (brightness: 175)
        {138, 126,  84},  // LED 5 (brightness: 138)
        {106,  99,  72},  // LED 6 (brightness: 106)
        { 49,  48,  43},  // LED 7 (brightness: 49)
        { 76,  74,  58}  // LED 8 (brightness: 76)
    },
    // Palette 57: viridis_gp
    {
        {255, 240,  13},  // LED 0 (brightness: 255)
        {159, 237,  38},  // LED 1 (brightness: 237)
        { 60, 209, 101},  // LED 2 (brightness: 209)
        { 23, 161, 141},  // LED 3 (brightness: 161)
        { 25, 120, 154},  // LED 4 (brightness: 154)
        { 41,  91, 153},  // LED 5 (brightness: 153)
        { 57,  57, 144},  // LED 6 (brightness: 144)
        { 69,  21, 124},  // LED 7 (brightness: 124)
        { 68,   0,  84}  // LED 8 (brightness: 84)
    },
    // Palette 58: plasma_gp
    {
        {255, 108,  67},  // LED 0 (brightness: 255)
        {255, 161,  31},  // LED 1 (brightness: 255)
        {250, 255,  11},  // LED 2 (brightness: 255)
        { 10,   5, 140},  // LED 3 (brightness: 140)
        { 65,   1, 158},  // LED 4 (brightness: 158)
        {112,   1, 167},  // LED 5 (brightness: 167)
        {157,   7, 164},  // LED 6 (brightness: 164)
        {203,  29, 138},  // LED 7 (brightness: 203)
        {235,  67, 102}  // LED 8 (brightness: 235)
    },
    // Palette 59: inferno_gp
    {
        {229,  74,  22},  // LED 0 (brightness: 229)
        {249, 113,  18},  // LED 1 (brightness: 249)
        {255, 158,  19},  // LED 2 (brightness: 255)
        { 20,   6,  63},  // LED 3 (brightness: 63)
        { 48,   4,  81},  // LED 4 (brightness: 81)
        { 81,   5,  94},  // LED 5 (brightness: 94)
        {122,  10,  88},  // LED 6 (brightness: 122)
        {163,  24,  66},  // LED 7 (brightness: 163)
        {201,  41,  42}  // LED 8 (brightness: 201)
    },
    // Palette 60: magma_gp
    {
        {234,  81,  81},  // LED 0 (brightness: 234)
        {255, 122,  80},  // LED 1 (brightness: 255)
        { 15,   8,  58},  // LED 2 (brightness: 58)
        { 35,   7,  81},  // LED 3 (brightness: 81)
        { 60,   8, 103},  // LED 4 (brightness: 103)
        { 92,   8, 114},  // LED 5 (brightness: 114)
        {130,  12, 112},  // LED 6 (brightness: 130)
        {168,  22, 102},  // LED 7 (brightness: 168)
        {204,  46,  88}  // LED 8 (brightness: 204)
    },
    // Palette 61: cubhelix_gp
    {
        {197, 135, 134},  // LED 0 (brightness: 197)
        {161, 132,  84},  // LED 1 (brightness: 161)
        { 98, 145,  48},  // LED 2 (brightness: 145)
        { 50, 133,  43},  // LED 3 (brightness: 133)
        { 13, 111,  47},  // LED 4 (brightness: 111)
        { 11,  70,  62},  // LED 5 (brightness: 70)
        { 15,  35,  59},  // LED 6 (brightness: 59)
        { 21,   6,  48},  // LED 7 (brightness: 48)
        {217, 148, 194}  // LED 8 (brightness: 217)
    },
    // Palette 62: abyss_gp
    {
        { 34,  99, 177},  // LED 0 (brightness: 177)
        { 26,  86, 164},  // LED 1 (brightness: 164)
        { 19,  75, 153},  // LED 2 (brightness: 153)
        { 14,  63, 138},  // LED 3 (brightness: 138)
        { 11,  52, 120},  // LED 4 (brightness: 120)
        {  8,  41, 102},  // LED 5 (brightness: 102)
        {  6,  31,  84},  // LED 6 (brightness: 84)
        {  4,  21,  65},  // LED 7 (brightness: 65)
        {  2,  14,  47}  // LED 8 (brightness: 47)
    },
    // Palette 63: bathy_gp
    {
        {102, 206, 232},  // LED 0 (brightness: 232)
        { 76, 172, 206},  // LED 1 (brightness: 206)
        { 55, 140, 185},  // LED 2 (brightness: 185)
        { 37, 105, 167},  // LED 3 (brightness: 167)
        { 29,  77, 148},  // LED 4 (brightness: 148)
        { 21,  51, 128},  // LED 5 (brightness: 128)
        { 15,  33, 100},  // LED 6 (brightness: 100)
        {  9,  17,  69},  // LED 7 (brightness: 69)
        {  5,   5,  36}  // LED 8 (brightness: 36)
    },
    // Palette 64: ocean_gp
    {
        {  0,  32,  32},  // LED 0 (brightness: 32)
        { 56, 212, 212},  // LED 1 (brightness: 212)
        { 29, 184, 203},  // LED 2 (brightness: 203)
        { 12, 155, 191},  // LED 3 (brightness: 191)
        {  6, 126, 165},  // LED 4 (brightness: 165)
        {  0,  47,  63},  // LED 5 (brightness: 63)
        {  0,  99, 139},  // LED 6 (brightness: 139)
        {  0,  81, 117},  // LED 7 (brightness: 117)
        {  0,  63,  95}  // LED 8 (brightness: 95)
    },
    // Palette 65: nighttime_gp
    {
        {  3,   3,  23},  // LED 0 (brightness: 23)
        {  7,   4,  38},  // LED 1 (brightness: 38)
        { 11,   5,  54},  // LED 2 (brightness: 54)
        { 18,   8,  72},  // LED 3 (brightness: 72)
        { 25,  12,  90},  // LED 4 (brightness: 90)
        { 35,  19, 100},  // LED 5 (brightness: 100)
        { 45,  26, 110},  // LED 6 (brightness: 110)
        { 60,  38, 125},  // LED 7 (brightness: 125)
        { 77,  51, 142}  // LED 8 (brightness: 142)
    },
    // Palette 66: seafloor_gp
    {
        { 70, 174,  96},  // LED 0 (brightness: 174)
        { 51, 155, 105},  // LED 1 (brightness: 155)
        { 34, 138, 114},  // LED 2 (brightness: 138)
        { 24, 115, 123},  // LED 3 (brightness: 123)
        { 14,  92, 131},  // LED 4 (brightness: 131)
        { 11,  69, 120},  // LED 5 (brightness: 120)
        { 10,  47, 109},  // LED 6 (brightness: 109)
        {  7,  32,  86},  // LED 7 (brightness: 86)
        {  6,  18,  66}  // LED 8 (brightness: 66)
    },
    // Palette 67: ibcso_gp
    {
        { 66, 118, 196},  // LED 0 (brightness: 196)
        { 50,  96, 180},  // LED 1 (brightness: 180)
        { 36,  75, 166},  // LED 2 (brightness: 166)
        { 27,  60, 144},  // LED 3 (brightness: 144)
        { 19,  45, 123},  // LED 4 (brightness: 123)
        { 13,  33, 100},  // LED 5 (brightness: 100)
        {  8,  21,  77},  // LED 6 (brightness: 77)
        {  5,  11,  54},  // LED 7 (brightness: 54)
        {  3,   3,  33}  // LED 8 (brightness: 33)
    },
    // Palette 68: copper_gp
    {
        { 56,  23,   6},  // LED 0 (brightness: 56)
        { 82,  37,  12},  // LED 1 (brightness: 82)
        {111,  53,  20},  // LED 2 (brightness: 111)
        {143,  71,  30},  // LED 3 (brightness: 143)
        {177,  92,  40},  // LED 4 (brightness: 177)
        {201, 119,  58},  // LED 5 (brightness: 201)
        {173, 121,  77},  // LED 6 (brightness: 173)
        {178, 138, 102},  // LED 7 (brightness: 178)
        {227, 149,  78}  // LED 8 (brightness: 227)
    },
    // Palette 69: hot_gp
    {
        { 80,   0,   0},  // LED 0 (brightness: 80)
        {134,   0,   0},  // LED 1 (brightness: 134)
        {189,  13,   0},  // LED 2 (brightness: 189)
        {241,  50,   0},  // LED 3 (brightness: 241)
        {255, 102,   0},  // LED 4 (brightness: 255)
        {255, 158,   0},  // LED 5 (brightness: 255)
        {255, 201,   0},  // LED 6 (brightness: 255)
        {255, 242,  13},  // LED 7 (brightness: 255)
        {191, 191,  82}  // LED 8 (brightness: 191)
    },
    // Palette 70: cool_gp
    {
        {  0, 255, 255},  // LED 0 (brightness: 255)
        { 11, 227, 255},  // LED 1 (brightness: 255)
        { 28, 194, 255},  // LED 2 (brightness: 255)
        { 70, 152, 255},  // LED 3 (brightness: 255)
        { 77,  78, 178},  // LED 4 (brightness: 178)
        {151,  71, 255},  // LED 5 (brightness: 255)
        {192,  30, 255},  // LED 6 (brightness: 255)
        {227,  11, 255},  // LED 7 (brightness: 255)
        {255,   0, 255}  // LED 8 (brightness: 255)
    },
    // Palette 71: earth_gp
    {
        {169, 151, 119},  // LED 0 (brightness: 169)
        {221, 195, 137},  // LED 1 (brightness: 221)
        {201, 175, 106},  // LED 2 (brightness: 201)
        {182, 156,  80},  // LED 3 (brightness: 182)
        {157, 138,  66},  // LED 4 (brightness: 157)
        {127, 119,  56},  // LED 5 (brightness: 127)
        { 85, 102,  46},  // LED 6 (brightness: 102)
        { 53,  79,  37},  // LED 7 (brightness: 79)
        { 28,  54,  28}  // LED 8 (brightness: 54)
    },
    // Palette 72: sealand_gp
    {
        {184, 236,  80},  // LED 0 (brightness: 236)
        {163, 223,  67},  // LED 1 (brightness: 223)
        {136, 210,  68},  // LED 2 (brightness: 210)
        { 98, 198,  87},  // LED 3 (brightness: 198)
        { 72, 176, 113},  // LED 4 (brightness: 176)
        { 50, 152, 136},  // LED 5 (brightness: 152)
        { 31, 114, 148},  // LED 6 (brightness: 148)
        { 16,  84, 146},  // LED 7 (brightness: 146)
        { 10,  58, 130}  // LED 8 (brightness: 130)
    },
    // Palette 73: split_gp
    {
        {206,  26,  26},  // LED 0 (brightness: 206)
        {218,  53,  43},  // LED 1 (brightness: 218)
        {222,  85,  72},  // LED 2 (brightness: 222)
        {214, 126, 113},  // LED 3 (brightness: 214)
        {198, 188, 177},  // LED 4 (brightness: 198)
        { 79, 130, 213},  // LED 5 (brightness: 213)
        { 54,  95, 203},  // LED 6 (brightness: 203)
        { 33,  67, 189},  // LED 7 (brightness: 189)
        { 18,  43, 168}  // LED 8 (brightness: 168)
    },
    // Palette 74: red2green_gp
    {
        {200,  20,  20},  // LED 0 (brightness: 200)
        {230,  49,  26},  // LED 1 (brightness: 230)
        {253,  87,  36},  // LED 2 (brightness: 253)
        {255, 136,  52},  // LED 3 (brightness: 255)
        {191, 185,  82},  // LED 4 (brightness: 191)
        {174, 233,  53},  // LED 5 (brightness: 233)
        {118, 209,  47},  // LED 6 (brightness: 209)
        { 70, 185,  38},  // LED 7 (brightness: 185)
        { 30, 160,  30}  // LED 8 (brightness: 160)
    }
};

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Get RGB color for a specific palette and LED index
 * @param paletteId Palette ID (0-74)
 * @param ledIndex LED index (0-8)
 * @param r Output: Red component (0-255)
 * @param g Output: Green component (0-255)
 * @param b Output: Blue component (0-255)
 */
inline void getPaletteColor(uint8_t paletteId, uint8_t ledIndex, uint8_t& r, uint8_t& g, uint8_t& b) {
    if (paletteId >= PALETTE_LED_COUNT || ledIndex >= PALETTE_COLORS_PER_PALETTE) {
        r = g = b = 0;
        return;
    }
    
    r = pgm_read_byte(&paletteLedColors[paletteId][ledIndex][0]);
    g = pgm_read_byte(&paletteLedColors[paletteId][ledIndex][1]);
    b = pgm_read_byte(&paletteLedColors[paletteId][ledIndex][2]);
}

/**
 * Get RGB color for a specific palette and LED index (returns as struct)
 */
struct PaletteColor {
    uint8_t r;
    uint8_t g;
    uint8_t b;
};

inline PaletteColor getPaletteColor(uint8_t paletteId, uint8_t ledIndex) {
    PaletteColor color;
    getPaletteColor(paletteId, ledIndex, color.r, color.g, color.b);
    return color;
}
